### ISSUE TITLE
POST with ID returns 400 Bad Request

### ISSUE THREAD

**Issue by Cory00** [jamesagnew/hapi-fhir#1111]
When sending a POST request with an id in the URL, the default behavior of HAPI is to send a 400 Bad Request response.
But in the FHIR standard, it's stated:

•	400 Bad Request - resource could not be parsed or failed basic FHIR validation rules
•	404 Not Found - resource type not supported, or not a FHIR end-point

Since the POST with id is not a valid FHIR endpoint, shouldn't the 404 Not Found be a more appropriate response code?

**Comment by jamesagnew** [comment]
HAPI's overall philosophy has been to avoid 404s unless strictly necessary, since they are the error you'll get in a whole bunch of other scenarios outside of HAPI's control (servlet didn't start correctly, revproxy isn't configured correctly,  client has the wrong base URL, etc.) 

In this case I think one could argue that this is a correct URL but the wrong verb for it (PUT vs POST), so just calling it an invalid request seems appropriate to me.
