### ISSUE TITLE
3.6 JPA server R4 Group.characteristic.valueQuantity fails

### ISSUE THREAD

**Issue by dconlan** [jamesagnew/hapi-fhir#1144]
**Describe the bug**
Hapi JPA server 3.6 - R4
If you include a characteristic of type quantity in a group resource you get the error:
```
Failed to call access method: ca.uhn.fhir.context.ConfigurationException: Search param value with path Group.characteristic.value is of unexpected datatype: class org.hl7.fhir.r4.model.Quantity"
```

**To Reproduce**
1. Go to 'https://fhirtest.uhn.ca/resource?serverId=home_r4&pretty=true&resource=Group'
2. Click on 'CRUD operations tab'
3. In the create contents add the text (this is a copy of the first example group but with a valueQuantity characteristic added)
```
{
  "resourceType": "Group",
  "identifier": [
    {
      "system": "http://someveterinarianclinic.org/fhir/NamingSystem/herds",
      "value": "12345"
    }
  ],
  "type": "animal",
  "actual": true,
  "code": {
    "text": "Horse"
  },
  "name": "John's herd",
  "quantity": 25,
  "characteristic": [
    {
      "code": {
        "text": "gender"
      },
      "valueCodeableConcept": {
        "text": "mixed"
      },
      "exclude": false
    },
    {
      "code": {
        "text": "owner"
      },
      "valueCodeableConcept": {
        "text": "John Smith"
      },
      "exclude": false
    },
        {
      "code": {
        "text": "value"
      },
      "valueQuantity": {
        "value": 148000.00,
        "unit" : "AUD"
      },
      "exclude": false
    }
  ]
}
```
4. Press the create button
5. See the error

**Expected behavior**
A group resource should be added

**Additional context**
My local jpa server shows the bug, but the R4 demo server also displays the same behavior, so I written the instructions using it.

**Comment by restevez-chs** [comment]
@dconlan, thanks for providing the exact steps to duplicate. i ran through them and duplicated the error.

I recently submitted a Pull Request: https://github.com/jamesagnew/hapi-fhir/pull/1134 for Issue #1124 

The issue is that `valueQuanity` needs to be used instead of correctly spelled `valueQuantity`.

I tried with this input and it resulted in a successful creation of a Group.

```json
{
  "resourceType": "Group",
  "identifier": [
    {
      "system": "http://someveterinarianclinic.org/fhir/NamingSystem/herds",
      "value": "12345"
    }
  ],
  "type": "animal",
  "actual": true,
  "code": {
    "text": "Horse"
  },
  "name": "John's herd",
  "quantity": 25,
  "characteristic": [
    {
      "code": {
        "text": "gender"
      },
      "valueCodeableConcept": {
        "text": "mixed"
      },
      "exclude": false
    },
    {
      "code": {
        "text": "owner"
      },
      "valueCodeableConcept": {
        "text": "John Smith"
      },
      "exclude": false
    },
        {
      "code": {
        "text": "value"
      },
      "valueQuanity": {
        "value": 148000.00,
        "unit" : "AUD"
      },
      "exclude": false
    }
  ]
}
```

Did this work for you? If so, perhaps you can put a Thumbs Up on the issue and/or PR for more attention.

Sincerely,
Ricky

**Comment by dconlan** [comment]
Do I need your fix to make valueQuanity to work?
When I use valueQuanity the result is a successful post, but there is no value stored in the resulting resource.

**Comment by restevez-chs** [comment]
@dconlan oh good catch. i just noticed that too. so all we've confirmed is the type-o, but still problems.

the PR i've submitted are the proposed changes. since i'm a new contributor i dont know if i have it 100% covered. so i've been looking forward to a response from HAPI FHIR code owners and regular contributors.

**Comment by dconlan** [comment]
This now seems to be fixed.
