### ISSUE TITLE
Bundle API is not pass the Authorization header for subsequent calls to the real resource APIs

### ISSUE THREAD

**Issue by kuasha** [jamesagnew/hapi-fhir#1156]
**Describe the bug**
We have an interceptor that validates bearer token and it works for all the APIs except the bundle POST API. The bundle seems to be issuing additional API request but is not forwarding HTTP headers. So when the API call come back to the service the interceptor will reject the call because the token is not present. 

**Expected behavior**
The bundle resource handler should passthrough the HTTP headers as it is. 

**Environment (please complete the following information):**
 - HAPI FHIR Version - mainline as of today: commit 4f16fea580e871033d1b912834b1f7c730a0b66c

**Comment by jamesagnew** [comment]
I'm not sure I follow this. Could you please provide a code snippet that
demonstrates the issue?

sent from my phone.

**Comment by kuasha** [comment]
Please allow me to clarify. We have an authorization interceptor that looks like:

```
public class MyAuthorizationInterceptor extends AuthorizationInterceptor {
    @Override
    public List<IAuthRule> buildRuleList(RequestDetails theRequestDetails) {
        String authHeader = theRequestDetails.getHeader("Authorization");
        // this throws exception if token is not valid and we catch and return 401
        verifyToken(authHeader); 
        return new RuleBuilder().allowAll().build();
    }
}
```
This basically validates the token passed using Authorization header and allow the user to continue.

Now we are sending a bundle request to retrieve two patients for example:
```
{
    "resourceType": "Bundle",
    "id": "bundle-request-simpleSummary",
    "type": "batch",
    "entry": [
        {
            "request": {
                "method": "GET",
                "url": "/Patient/54"
            }
        },
        {
            "request": {
                "method": "GET",
                "url": "/Patient/53"
            }
        }
    ]
}
```
At this point the server is making two different calls to itself but not forwarding the token. So, the authorization intercepter will reject the call.

Let me know if you have any more question and will appreciate any suggestion about possible best way to address this if there a known pattern for this.

**Comment by treaston2** [comment]
@jamesagnew our issue looks similar to this post. Is there any code sample we could refer to to handle passing our authorization header when calling a batch/transaction? 

https://groups.google.com/forum/#!searchin/hapi-fhir/bundle$20interceptors%7Csort:date/hapi-fhir/RrDLQ3e5PEs/TKiz8kEfBAAJ

> 1) I'm assuming that verification of the OAuth authentication token happens in incomingRequestPreProcessed. Are you saying that it is it possible for the user to bypass these when I only register the interceptor in JpaServerDemo-class? So I have to register it in DaoConfig. Could you give a tip to how I do that?  

Correct. Well, sort of.. I guess what I'm saying is that depending on how you write your interceptor it *might* be possible to bypass the security checks if you only register your interceptor with the server and not with the DAOs. The reason for this is that RestfulServer calls the interceptor methods for each call. So, when you get a read or a create or update or whatever, you'll get a call to your interceptor. This is the normal case, and it's easy to code for.

Transactions make this messy though. With a transaction/batch, you can stuff a bunch of creates, or updates, or even nested transactions/batches with their own creates into a bundle and send this to the server to process. If you write your interceptor to handle transactions and go through them looking for what they are doing, you will be secure. This is tricky though, since transactions have lots of ways of doing things. If I was trying to hack a FHIR server, that would certainly be the path I would try first. :)

If you register your interceptor both with the server and with the DaoConfig you get better security, since the JPA server analyses the transaction, splits it into individual operations (read/create/etc.) and calls the interceptor once for each of these operations. This means you are much less likely to miss something. To do this, look in your Spring Config for where the DaoConfig bean is being created and add interceptors to it using its "interceptors" property.

I don't have any publicly posted examples of this (yet) but if our public server was doing this, it would be with a call to daoConfig.setInterceptors(...); in the daoConfig() method here: https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-uhnfhirtest/src/main/java/ca/uhn/fhirtest/config/TestDstu2Config.java

> 2) I can't find the HttpRequest in incomingRequestPreHandled. I can find the resource, but not the http-request. What would be the best way to relay the 'real authenticated user' and other details coming from the oauth server to the other interceptor methods such as incomingRequestPreHandled and outgoingResponse (which does have the http request)? 

Yeah, this is a pain. I'd like "incomingRequestPreHandled" to have a copy of the servlet request but getting that up that chain from the resource provider into the DAO was a nuisance so I haven't gotten there yet.

In our internal implementations, we're using Spring Security so this isn't actually an issue. The way this works is Spring Security has a listener which is registered outside of anything HAPI related (you declare it in web.xml and it is invoked before HAPI even gets ahold of the request). SpringSec checks the incoming request, parses and validates the request bearer token and then puts an authorization object in a ThreadLocal variable. The incomingRequestPreHandled methods when pull that object from the ThreadLocal and inspect it.

You could probably do something similar... Check the token in incomingRequestPreProcessed, stuff it in a ThreadLocal, then use it in incomingRequestPreHandled.

Hopefully at some point soon we can just get HAPI to pass the servletrequest all the way up the chain though. That would be useful for lots of reasons...

Cheers,
James

**Comment by treaston2** [comment]
@jamesagnew Do you think this approach would work to pass the authorization header? 
https://stackoverflow.com/questions/16190699/automatically-add-header-to-every-response

**Comment by jamesagnew** [comment]
Hi Maruf, Brian,

I was actually able to replicate this locally- I agree that headers don't
seem to make it to the interceptor for sub-read-requests in a transaction.

I've just committed a fix for this, will push a new 3.7.0 snapshot build to
Maven Central at some point in the next 24 hours.

Cheers,
James

**Comment by treaston2** [comment]
@jamesagnew This is great. Thank you Sir!

**Comment by treaston2** [comment]
@jamesagnew  The fix works. Thanks!
