### ISSUE TITLE
Subscription handling question

### ISSUE THREAD

**Issue by tehrafe** [jamesagnew/hapi-fhir#1240]
Hello,
We are using hapi-fihr on a current research project and was wondering how the API handles subscriptions. If we don't use the JPA server project, are we supposed to implement our own interceptors to handle the subscriptions or are there calls in the library to handle them? Searching the documentation, we could only found calls to handle the subscription resources and none to handle their mechanics.

**Comment by jamesagnew** [comment]
Hi @tehrafe 

FYI- Please use our Google Group to ask questions instead of opening a ticket. See here for information: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

If you aren't using the JPA project, you will unfortunately need to implement the subscription processing logic yourself. The JPA project might be useful as a guide however!
