### ISSUE TITLE
ImagingStudy search on accession is not working

### ISSUE THREAD

**Issue by laurentenhoor** [jamesagnew/hapi-fhir#1284]
**Describe the bug**
Search on accession does not seem to work for in the ImagingStudy API.

**To Reproduce**
1. Find a study with an accession (e.g. [http://hapi.fhir.org/baseDstu3/ImagingStudy?_id=1711501](http://hapi.fhir.org/baseDstu3/ImagingStudy?_id=1711501))
2. Search based on this accession: [http://hapi.fhir.org/baseDstu3/ImagingStudy?accession=PLAC](http://hapi.fhir.org/baseDstu3/ImagingStudy?accession=PLAC)

**Expected behavior**
We expected to find the result from reproduction step 1. However no results are returned.

**Environment (please complete the following information):**
 - HAPI FHIR Version [http://hapi.fhir.org/baseDstu3](http://hapi.fhir.org/baseDstu3)

**Comment by fil512** [comment]
Hi Lauren,

The "PLAC" in that ImagingStudy describes the type of accession number, not
the accession number itself.  If you want to search by accession number,
you would need to search by the "value" of the accession for that resource:

http://hapi.fhir.org/baseDstu3/ImagingStudy?accession=sVqOqShYA5Umr0ks%2BcHkZw%3D%3D

Sincerely,
Ken

**Comment by laurentenhoor** [comment]
Thanks! 

I might be misunderstanding the spec, but I do not see an accession parameter specified in the search parameters for ImagingStudy:
http://hl7.org/implement/standards/fhir/imagingstudy.html#search

Reading the spec I am expecting something like:
`identifier=accession|6283726`

**Comment by dmuylwyk** [comment]
@laurentenhoor, you've linked to the R4 version of ImagingStudy but you indicated you're working with the STU3 version.

Compare:

- https://www.hl7.org/fhir/STU3/imagingstudy.html
- http://hl7.org/fhir/imagingstudy.html

In STU3, we have both ImagingStudy.accession and ImagingStudy.identifier; however, in R4 we have only ImagingStudy.identifier.

**Comment by laurentenhoor** [comment]
Thanks! So what is the correct way to search on accession in version 4?

**Comment by dmuylwyk** [comment]
See the implementation notes here:

http://hl7.org/fhir/imagingstudy.html#notes

and the identifier search parameter here:

http://hl7.org/fhir/imagingstudy.html#search

In fact, CTRL-F on that page for "accession" will tell you everything you need to know. : )

Regarding your initial ask (point 2 above), there's no standard search parameter for ImagingStudy.accession.type (STU3) or ImagingStudy.identifier.type (R4). However, you can always create your own custom search parameter.

If you have additional questions, please use our Google Group to ask questions instead of opening a ticket. See here for information: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
