### ISSUE TITLE
ResourceBinding fails to choose correct method due to SearchMethodBinding matching issue

### ISSUE THREAD

**Issue by tuomoa** [jamesagnew/hapi-fhir#1421]
Hello @jamesagnew,

I already commented on the actual commit (https://github.com/jamesagnew/hapi-fhir/commit/19954fa#r34196172), but decided to make an issue after all.

I think the `ALLOWED_PARAMS` change b442982310ef5402393d8a06fa151a54f03d4a7a (with change 19954fa252af183ffa09069a10821f6e2d2426a4) is causing regression in 3.7.0 and later. I think the `incomingServerRequestMatchesMethod` is not correctly handling underscore prefixed parameters anymore.

We have (for example) two methods in our resource provider, one does not support `_include` parameter but the other does:

```
public Bundle searchA(@RequiredParam(name = CarePlan.SP_PATIENT) IdType patientId) { ... }

public Bundle searchB(@RequiredParam(name = CarePlan.SP_PATIENT) IdType patientId, @IncludeParam(..) List<Include> includes) { ... }    
```

When upgrading to the 3.8.0 the provider is calling the method without `_include` parameter even though we are using it in the request (we also have other underscore prefixed parameters in search methods, such as `_tag`). After debugging for a while I think this is accidentally ignoring too many parameters prefixed with underscore. (And therefore when checking if there was unknown params this `incomingServerRequestMatchesMethod` method ends up returning true instead of false and therefore the `ResourceBinding` `getMethod(RequestDetails theRequest)` incorrectly returns the method without `_include` param).

WDYT?

I think this is also related to the #1373

**Comment by ruoat** [comment]
@jamesagnew are there any plans to check this? This blocks our migration from Hapi 3.6.0

**Comment by tuomoa** [comment]
@jamesagnew @dmuylwyk any chance someone could address this issue?

**Comment by jamesagnew** [comment]
A pull request with a test demonstrating the issue (or a fix) would be welcomed- I'm not sure I understand what exactly is wrong here.

If you have two methods where the only difference is the absence or presence of an `@Include` parameter, why not just collapse these into one method and just do an if-null check on the include parameter?

**Comment by tuomoa** [comment]
Hello @jamesagnew, I just created a pull request #1492 with a failing test case demonstrating the issue with underscored parameters and binding matching. Let me know what do you think.

**Comment by jamesagnew** [comment]
Fixed in 7700bb85ef

**Comment by tuomoa** [comment]
Hello @jamesagnew,

Thanks for that fix but I think it's incomplete. If you take a look at https://www.hl7.org/fhir/STU3/search.html#2.21.1.1 there are multiple other underscored parameters such as `_tag`, `_has` that are now handler incorrectly. There are also some normal underscored field parameters such as `_language` (which is also in the special handled set).

Would it be possible to make the handling better to work with those standard parameters as well?

Let me know what do you think.

**Comment by jamesagnew** [comment]
Honestly, my recommendation here is just to create a single method that takes all of these parameters and handle your selection logic inside that method.

I realize that it would be nice to have a fancy system that selects between various permutations of all of the meta-parameters and always picks the right one, but this is not trivial. The change you reference in the top post was made in order to fix other issues, and it's really hard to solve this without causing other regressions. Not impossible by any means, but **much** more work than I am willing to spend on this right now.

I'd be willing to accept a pull request that addresses this of course (provided that it was a clean solution and did not cause other regressions), and as always it's possible that someone with a support contract might file a ticket on this, in which case a dedicated support engineer would take a crack at it.
