### ISSUE TITLE
Securing Data at REST

### ISSUE THREAD

**Issue by adityakmehta** [jamesagnew/hapi-fhir#1497]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**I am trying to encrypt data at REST of the data created using HAPI FHIR JPA server. I see that in the Table HFJ_RESOURCE, the column HASH_256 has some keys. Is it the one securing and encrypting my data? If not, how can I encrypt sensitive information using HAPI FHIR? Is that supported/possible?**
A clear and concise description of what the feature request is. Please include details about what problem you are ultimately trying to solve (i.e. what are you building with HAPI FHIR) and how this feature would help.

**Environment (please complete the following information):**
 - HAPI FHIR Version : HAPI FHIR JPA Server DSTU2
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**

**Comment by jamesagnew** [comment]
The HASH_256 column is used for efficient duplicate checking, it has no security function currently. There is no application level encryption-at-rest built into HAPI FHIR.

The easiest way to do encryption at rest is to encrypt at the underlying database level, or even at the disk level.

**Comment by jamesagnew** [comment]
I'm closing this, as it is more of a question (please note: the mailing list should be used for questions). If you feel this is an incorrect assessment please comment here.

**Comment by schadha101** [comment]
jamesagnew - "_The easiest way to do encryption at rest is to encrypt at the underlying database level_"

To not affect performance we would like to encrypt only the PHI - patient, vitals and medication etc since Not all stored in FHIR is PHI. 

The database tables in HAPI FHIR are below. If we want to encrypt for example resources: patient, observation, medication resources, what tables should we encrypt?   Seems table are not on a resource basis but is a generic platform to store resources of any type.


+-------------------------------+
| Tables_in_hapifhir |
+-------------------------------+
| HFJ_FORCED_ID |
| HFJ_HISTORY_TAG |
| HFJ_IDX_CMP_STRING_UNIQ |
| HFJ_RESOURCE |
| HFJ_RES_LINK |
| HFJ_RES_PARAM_PRESENT |
| HFJ_RES_REINDEX_JOB |
| HFJ_RES_TAG |
| HFJ_RES_VER |
| HFJ_SEARCH |
| HFJ_SEARCH_INCLUDE |
| HFJ_SEARCH_RESULT |
| HFJ_SPIDX_COORDS |
| HFJ_SPIDX_DATE |
| HFJ_SPIDX_NUMBER |
| HFJ_SPIDX_QUANTITY |
| HFJ_SPIDX_STRING |
| HFJ_SPIDX_TOKEN |
| HFJ_SPIDX_URI |
| HFJ_SUBSCRIPTION_STATS |
| HFJ_TAG_DEF |
| SEQ_CNCPT_MAP_GRP_ELM_TGT_PID |
| SEQ_CODESYSTEMVER_PID |
| SEQ_CODESYSTEM_PID |
| SEQ_CONCEPT_DESIG_PID |
| SEQ_CONCEPT_MAP_GROUP_PID |
| SEQ_CONCEPT_MAP_GRP_ELM_PID |
| SEQ_CONCEPT_MAP_PID |
| SEQ_CONCEPT_PC_PID |
| SEQ_CONCEPT_PID |
| SEQ_CONCEPT_PROP_PID |
| SEQ_FORCEDID_ID |
| SEQ_HISTORYTAG_ID |
| SEQ_IDXCMPSTRUNIQ_ID |
| SEQ_RESLINK_ID |
| SEQ_RESOURCE_HISTORY_ID |
| SEQ_RESOURCE_ID |
| SEQ_RESPARMPRESENT_ID |
| SEQ_RESTAG_ID |
| SEQ_RES_REINDEX_JOB |
| SEQ_SEARCH |
| SEQ_SEARCH_INC |
| SEQ_SEARCH_RES |
| SEQ_SPIDX_COORDS |
| SEQ_SPIDX_DATE |
| SEQ_SPIDX_NUMBER |
| SEQ_SPIDX_QUANTITY |
| SEQ_SPIDX_STRING |
| SEQ_SPIDX_TOKEN |
| SEQ_SPIDX_URI |
| SEQ_SUBSCRIPTION_ID |
| SEQ_TAGDEF_ID |
| TRM_CODESYSTEM |
| TRM_CODESYSTEM_VER |
| TRM_CONCEPT |
| TRM_CONCEPT_DESIG |
| TRM_CONCEPT_MAP |
| TRM_CONCEPT_MAP_GROUP |
| TRM_CONCEPT_MAP_GRP_ELEMENT |
| TRM_CONCEPT_MAP_GRP_ELM_TGT |
| TRM_CONCEPT_PC_LINK |
| TRM_CONCEPT_PROPERTY |
+-------------------------------+

**Comment by dumip** [comment]
It would be really useful to be able to encrypt a small subset of information, e.g. data that can be used to identify persons, patients, etc. Is there any plan for such feature?
