### ISSUE TITLE
Date match bug

### ISSUE THREAD

**Issue by fil512** [jamesagnew/hapi-fhir#1499]
See https://github.com/jamesagnew/hapi-fhir/tree/date-match-bug for a failing test that demonstrates the error.

The source of the bug is the timezone shift calculation in DateRangeParam.getUpperBoundAsInstant()

Recommended fix:
Add two new columns to ResourceIndexedSearchParamDate that store the low and high date (with no time) as an integer in the format 20190921.  When the search is for a date without a time, use this column for the search instead of the date column.

**Comment by Romanow88** [comment]
Just encountered this as well just now. 

I do not know why this was implemented in this way. I agree that the date range should account for time, but rather then trying to play with timezone shifts, it's better to just unwrap the date into low-high via appending 00:00:00.0000000 and 23:59:59.9999999 accordingly.

**Comment by Romanow88** [comment]
@jamesagnew  I'm willing to submit a PR if you think this is valid.

**Comment by jamesagnew** [comment]
Wouldn't that approach suffer from the same issue? You'd have to pick a timezone to apply that 00:00 and 23:59 to..

**Comment by Romanow88** [comment]
I would use the same time zone that is used to compute the date of creation of the resource. That way what we display on the response is in sync with the query.

Without knowing the users timezone we will net be able to determine the correct time that they would need, but at least we would be consistent with what is in the creation date.

Right now when I request resources for 21-02-2020, the current implementation unwraps that into 20-02-2020 12:30:00 - 21-02-2020 13:30:00 for the server and client in the same timezone.

I would propose to unwrap it to 21-02-2020 00:00:00 - 21-02-2020 23:59:59 using the server timezone, if no timezone is provided.

**Comment by jamesagnew** [comment]
You mean like you'd just use the underlying OS timezone and just choose a
24-hour period that aligns with that timezone?

I'm not 100% sure but I feel like that's already what we're doing....

**Comment by Romanow88** [comment]
We are doing that, true, but in a weird way. What we do is: Take a date, and make it a time by just taking the midnight. Then to get the time range we create two times based on that, one is -12 hours, other is +12 hours. The problem is that if the resource was created after midday on that date, it will not be included in the search. 

Example:
1. We have a resource a resource that was created at 21-02-2020 17:00:00
2. A search is triggered with the date param set to 21-02-2020 
3. 21-02-2020 is unwrapped to 21-02-2020 00:00:00
4. 21-02-2020 00:00:00 -> from  20-02-2020 12:30:00  to 21-02-2020 13:30:00
5. The resource from 1 will not be included.
