### ISSUE TITLE
XML/JSON parsers should fail for the elements that can't be recognised.

### ISSUE THREAD

**Issue by czajek** [jamesagnew/hapi-fhir#152]
We make use of HAPI parsers for the validation purpose. Right now parsers accept content that contains unsupported elements (it ignores such elements). For example content below passes validation: 

```
<Patient>
    <someUnsupportedElement/>
</Patient>
```

Is it possible to configure parsers so it fails in mentioned scenario.

**Comment by czajek** [comment]
It's the same problem with single element added twice for example:
<Patient>
    <active value="true"/>
    <active value="true"/>
</Patient>

**Comment by jamesagnew** [comment]
FYI- My plan for addressing this issue is to add a 'strict' mode to the parser, probably next week some time.

Per a discussion with Bill De Beaubien, we should also error out if a resource contains an empty tag (i.e. no term)

**Comment by izi** [comment]
Is it still on your roadmap? Will this be a part of 1.0 or 1.1 release?

**Comment by jamesagnew** [comment]
Hi All,

This is still very much on the roadmap. Unfortunately it did not make it in
for the 1.0 release, which I wanted to get out quickly because there are a
few minor breaking API changes needed for the harmonization work we're
doing with the HL7.org Java RI. This should land in the development builds
fairly soon.

Cheers,
James
