### ISSUE TITLE
More than one Resource Provider per FHIR Resource type

### ISSUE THREAD

**Issue by whbath** [jamesagnew/hapi-fhir#165]
Hi,
We have the challenge where the data for our resources may be contributed by multiple systems. E.g. for Observations, we have three systems that surface:
- Consumer vitals / observations
- Clinical vitals
- Lab results

Can you only ever have one Resource Provider for Observation, or if we provider for each system will HAPI aggregate across the 3 and surface up the results as a single result?

**Comment by jamesagnew** [comment]
Hi there, to be honest I'm not sure what HAPI would do if you created multiple resource providers with the same resource type.

From the FHIR perspective, the problem you're solving is tricky. I know this because we have tried to solve it too at UHN with a few resource types that are backed by multiple solutions. The problem is that FHIR expects yu to be able to read a resource by ID (e.g. Observation/123) so if there are two sources of observations, the resourceprovider needs to know which source to look in for "123".

We have solved this by using a prefix, e.g. in our read method "Observation/A100" looks in one database and "Observation/B100" looks in another. Our search method searches both databases. The only was we could make this work is to have a single resource provider that delegates to code querying one or both backing databases depending on the operation.

That aggregation kind of needs to be manual though, I don't think I see a way that HAPI could do it automatically. If you have ideas I'm certainly not opposed though...
