### ISSUE TITLE
Documentation error (Annotations of Delete)

### ISSUE THREAD

**Issue by RazStorm** [jamesagnew/hapi-fhir#174]
Not sure where to post issues with the documentation so here goes:

Shouldn't the 
@Delete()
public void deletePatient(@IdParam IdDt theId)

in the documentation (http://jamesagnew.github.io/hapi-fhir/doc_rest_operations.html#Instance_Level_-_Delete) really be:
@Delete(type = "Patient.class") .....

Otherwise how does HAPI know what resource to delete on the server?

**Comment by jamesagnew** [comment]
Hi @RazStorm , 

Thanks for the report! Always nice to have people fact checking the docs. :)

The `type=` attribute is actually generally not needed because you would typically put this method in an IResourceProvider class on a server. In that case, the resource type is inferred from the type of the resource provider. That attribute only needs to be set on annotation clients, which is mentioned in the [javadoc](http://jamesagnew.github.io/hapi-fhir/apidocs/ca/uhn/fhir/rest/annotation/Delete.html#type--). 

Do you think this is sufficient, or is there some way we could make it more clear?

**Comment by jamesagnew** [comment]
Closing old issues, please feel free to comment/re-open if you feel that this was closed in error.
