### ISSUE TITLE
/fhir/CodeSystem?_has:ImplementationGuide:resource:_id=XXX not working

### ISSUE THREAD

**Issue by rgeimer** [jamesagnew/hapi-fhir#1751]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
The _has modifier does not seem to be working correctly for CodeSystem resources in STU3 repositories. 

**To Reproduce**
Create a CodeSystem resource called XXX
Create an ImplementationGuide resource and add XXX to ImplementationGuide.resource
Do a GET on /fhir/CodeSystem?_has:ImplementationGuide:resource:_id=XXX
Note that 0 results are returned. 

**Expected behavior**
CodeSystem XXX would be returned in the searchset

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version: 4.2
 - OS: [e.g. iOS]: Linux
 - Browser [e.g. chrome, safari]: None (using Postman)

**Additional context**
None

**Comment by tadgh** [comment]
Hey there! I just ran a small test to try to replicate your issue, but now that I think about it, you may have misunderstood a small part of how the `_has` query works. Let's take a look at the [example from the docs](https://www.hl7.org/fhir/search.html#has): 
```http 
GET [base]/Patient?_has:Observation:patient:code=1234-5
```
This query is saying `Get me all the patients, where they have an observation which has a code of 1234-5`. Note that the final query term `code=1234-5` is the code of the _observation_ and not the _patient_. In the case of your query: 
```http
GET [base]/fhir/CodeSystem?_has:ImplementationGuide:resource:_id=XXX`
```
That query is equivalent to saying: `Get me all the CodeSystems that have an implementation guide who's _id(the ImplementationGuide _id) is XXX`.

You _could_ do this via chaining, like so: 
```http
GET [base]/fhir/CodeSystem?_has:ImplementationGuide:resource:resource.id=XXX
```
(Note that this currently doesn't work, but will work once #1760 is merged). 

Or alternatively, since you already know the ID of the CodeSystem, you could do the much simpler: 
```http
GET [base]/CodeSystem/XXX
```
Closing this for now as I do not believe it to be a bug
