### ISSUE TITLE
BaseResource has no way to reference a contained BaseResource

### ISSUE THREAD

**Issue by Gyannea** [jamesagnew/hapi-fhir#194]
Since it is necessary to reference a contained resource from the parent resource in order that the contained resource be encoded into an XML or JSON string, there needs to be a generic way for a resource to reference the contained resource. The BaseResource DOES have the ability to add contained resources so it needs a generic capability to reference it or it will be lost.

Actually I think the need to reference contained resources to have them encoded makes no sense. Why would I include a contained resource if I did not think it was important?

**Comment by jamesagnew** [comment]
Hi @Gyannea ,

I'm a bit confused at what you're trying to do, can you give a bit more detail? A contained resource only has meaning in FHIR if it is referenced from either the parent/containing resource, or from another contained resource.

What would this be used for? I.e. what would be the use for a contained resource with no references to it?

**Comment by Gyannea** [comment]
First I do not believe there should be a need to have a reference to a contained resource. If one goes through the effort of putting a resource inside a resource, it's pretty clear that the contained resource is important to the resource containing it! Its just like a child element in xml.
That aside, since one needs to include a reference in order to keep the retained resource in the resource (if one doesn't it vanishes when the resource is actually created for transmission) then the BaseResource needs a method to reference the contained resource. The BaseResource DOES include a method to add a contained resource, but it has no method to add a reference to that resource!
Consider a simple method to add a resource inside a parent resource:
    public void insertResourceInResouce(BaseResource resource, BaseResource resourceToInsert)
    {
        ContainedDt containedDt = new ContainedDt();
        ArrayList<IResource> resourceList = new ArrayList<IResource>();
        resourceList.add(resourceToInsert);
        containedDt.setContainedResources(resourceList);
        resource.setContained(containedDt);
        // Now add reference to that contained resource
        resource.?
    }

**Comment by jamesagnew** [comment]
Hi @Gyannea ,

The problem here is that HAPI FHIR is just an implementation of a specification, and one of our main goals is to create software that faithfully adheres to that specification. According to the rules of FHIR, a contained resource is only valid if it is referenced from the outer (containing) resource somehow. If we create a method for adding contained resources with no references, this is just creating a way for people to use HAPI to create invalid FHIR content, and this runs counter to the goals of the project.

You can see a copy of the rule we are following [here](http://hl7-fhir.github.io/references.html#1.14.0.1)

> A contained resource can only be included in another resource if something in the resource actually refers to it:
> 
> Resources that are contained inline do not "inherit" context from their parent resource. For instance, if  the parent resource contains a "subject", and the contained resource also has a "subject" element  defined, thre is no implication that the contained resource has the same subject as the parent resource. 

I can see two paths forward here however:
* You can define an extension in your outer resource which points to the contained resource. As long as there is some link you are fine, so this would let you have your content as you want it and still be valid.
* You could describe the mapping you are trying to do on the FHIR mailing list or on the Skype implementors chat. The people there may have ideas on how to do the mapping you are trying to do in a valid way. Let me know if you want to pursue this and need to be pointed in the direction of these resources.
* You can propose a change to the rules of FHIR itself, either on their mailing list or on their issue tracker if you feel like the FHIR rules are wrong.

Cheers,
James

**Comment by Gyannea** [comment]
James,
That is why the BaseResource needs to be able to create a reference. To make it FHIR compliant, if a BaseResource can add a contained resource, it needs a method to to add a reference to that resource! At the moment I CAN add the references but I have to do it in the actual resource, not the BaseResource (which doesnt make sense since one needs a reference!)

**Comment by jamesagnew** [comment]
I get what you're saying, but even if we add such a method to BaseResource there is nowhere for us to actually encode such a reference when we serialize the resource. This is the basic problem, we need to be able to serialize valid FHIR.

Why not just add an extension though? There certainly are methods on BaseResource for adding extensions, and that would allow you to do this with a valid serialization.
