### ISSUE TITLE
IdentifierTypeCodesEnum missing values

### ISSUE THREAD

**Issue by Gyannea** [jamesagnew/hapi-fhir#197]
When mapping PCD-01 to FHIR where an XDSb type patient identifier is used PID-3 essentially appears as follows:
28da0026bc42484^^^Android-Receiver&1.19.6.24.109.42.1.3&ISO^PI

Okay, now comes the problem of mapping this to the identifier. According the the FHIR example "XDS patient" the identifier is expressed as follows: (Sorry, try as I might I could not get xml to display at all and I could not get JSON to format nicely. The markup does not work well.)
*"identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v2/0203",
            "code": "MRN"
          }
        ]
      },
      "system": "urn:oid:1.2.3.4.5",
      "value": "89765a87b"
    }
  ],*

which for me should be:
*"identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v2/0203",
            "code": "MRN"
          }
        ]
      },
      "system": "urn:oid:1.19.6.24.109.42.1.3",
      "value": "28da0026bc42484"
    }
  ],*
The HAPI-FHIR library forces one to use the **IdentifierTypeCodesEnum** for the code value and the option MRN does not exist. MRN is also not present at http://hl7.org/fhir/v2/0203/, the closest one gets is MR. In the V2 docs I only see MR in the Identifier list but the V2 docs use MRN in PID-3 so I don't know what is going on. Since MR is Medical Record Number which MRN is also likely to be ...

What is present at http://hl7.org/fhir/v2/0203/ is 'XX' and 'U'. But there is no way to express those either and I need them.

**Comment by jamesagnew** [comment]
Hi @Gyannea ,

This is actually just a case of the FHIR example being wrong. The code they use in the example should be "MR" and not "MRN". Oddly enough you're the second person to run into this issue. I filled a bug request against FHIR itself ( [here](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=8382) ).

If you manually update your copy of the example that should get you up and running, it will be fixed in the next FHIR release.

Cheers,
James
