### ISSUE TITLE
bug with ValueSet$expand with filter

### ISSUE THREAD

**Issue by mohammadfarooqi** [jamesagnew/hapi-fhir#2189]
I've investigated this issue further and here are my findings.

we are trying to search for the term "mixed". 
![image](https://user-images.githubusercontent.com/10905290/99851668-72986c00-2b4d-11eb-91ba-2bf64529880f.png)

we can see here that at least 1 result should come up:
![image](https://user-images.githubusercontent.com/10905290/99851726-8e9c0d80-2b4d-11eb-8bde-8f7b4b95488f.png)

and we verify the codesystem has it as well:
![image](https://user-images.githubusercontent.com/10905290/99851758-a07db080-2b4d-11eb-85b6-0fa2b32b5b57.png)

we also verify that the $expand?filter= does give back some "selective" results. for example here:
![image](https://user-images.githubusercontent.com/10905290/99851916-ef2b4a80-2b4d-11eb-8e91-953f9784daa6.png)

Possibly related to: https://github.com/jamesagnew/hapi-fhir/issues/1946

**Comment by dmuylwyk** [comment]
FWIW, I've been working with @mohammadfarooqi between other tasks to zero in on the actual problem here. While this is present in an inaccessible server, it's likely not limited to this implementation. There's a CodeSystem with more than 90K concepts. The ValueSet includes the entire CodeSystem. This may be related to the expansion or the trouble may have started when the CodeSystem and ValueSets were created / pre-expanded.

This may also be related to #1946 or even #2175 

Next steps are to turn these observations into a minimal reproducible example to make this ticket actionable.

**Comment by dmuylwyk** [comment]
@jamesagnew's changes have partly resolved this issue. See @frankjtao and @IanMMarshall PR #2175, which will support left-matching _by string token_, case-insensitive once merged.
