### ISSUE TITLE
GET http://fhirtest.uhn.ca/baseDstu2/Slot?fb-type=BUSY&_format=xml returns 0

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#230]
Such a request always return 0 results, however there are some at server. 

Also API contains SlotStatusEnum which set status in lowercase.

**Comment by jamesagnew** [comment]
Hi Andrew,

The fb-type search param is actually a "token" search param, which means it follows FHIR's token rules. You would need to do this search as http://fhirtest.uhn.ca/baseDstu2/Slot?fb-type=|FREE because the code is FREE and you aren't searching by system.

One thing to note, these resources are actually invalid, as the codes defined by FHIR are in lower case (the value should be 'free', not 'FREE').

**Comment by gansoper** [comment]
Thank you for your explanations James!
