### ISSUE TITLE
Pick up the latest dstu2 changes to _include

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#240]
See: https://www.hl7.org/fhir/search.html#include
As far as I can tell, what used to be
http://fhirtest.uhn.ca/baseDstu2/MedicationOrder&_include=*
should now be
http://fhirtest.uhn.ca/baseDstu2/MedicationOrder?_include:recurse=MedicationOrder:*

My reading of the spec is that the :recurse shouldn't be required, but HealthIntersections at least requires it.

**Comment by jamesagnew** [comment]
Hi Bill,
Recursion used to be unspecified- you'd do `_include=foo` and the server got to choose whether or not to recurse. As of DSTU2 at search would be non-recursive and you would specify `_include:recurse=foo` if you wanted it to recurse.

Hapi should support both- is that not working for you? This sounds like maybe an issue needs to be filed against [HealthIntersections Server](https://github.com/grahamegrieve/fhirserver) :)

**Comment by jportner** [comment]
Since this falls under the same topic, I'm replying to this thread rather than open a new issue...

The [spec](https://www.hl7.org/fhir/search.html#include) outlines three parameters for _include, each separated by a ":" character...

1. The name of the source resource from which the join comes
2. The name of the search parameter which must be of type reference
3. (Optional) A specific of type of target resource (for when the search parameter refers to multiple possible target types)

HAPI only appears to support the first two parameters.
Support for the third (optional) parameter would be excellent.
E.g. `GET /baseDstu2/CarePlan?_include=CarePlan:activityreference:Goal` would only include activityreference resources that are of the Goal type.
