### ISSUE TITLE
$everything returns a bundle with no type set

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#247]
Which makes the bundle schema-invalid

**Comment by wdebeau1** [comment]
bundles returned from paging links such as next and previous also have this issue

**Comment by jamesagnew** [comment]
Checking in a fix shortly- The fix is actually not entirely as you requested though, hopefully it's ok.

The ID on the resource still gets set to the UUID when we parse. We need this because it's used if you have references to the resource from other resources in the bundle. I've disabled encoding these though in the parser, so the end result should be identical. Let me know if this doesn't solve your problem.
