### ISSUE TITLE
HAPI doesn't set an accept header by default

### ISSUE THREAD

**Issue by dionmcm** [jamesagnew/hapi-fhir#250]
By default, HAPI does't set an accept header by default. Also unless explicitly set, HAPI doesn't set the _format parameter.

As a result requests to a FHIR server by default don't specify an expected/required response format, yet HAPI expects to get application/xml-fhir or application/json-fhir or it will throw a ca.uhn.fhir.rest.client.exceptions.NonFhirResponseException. Some servers (like Ontoserver) will respond with text/html if format is not specified which is useful for naive clients or users pointing a browser at these REST urls.

A client should always specify the format it expects - please change HAPI to always specify the format it is expecting. I've created a ticket against the FHIR specification to add this clarification. http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=8978

**Comment by bdenton** [comment]
I would further this comment in saying that the client should also be tolerant of servers that just respond with application/xml, text/xml, or application/json… all without the ‘-fhir’ or ‘+fhir’ part. Not all servers are going to be able to produce those non-conventional content-types especially with things like proxies and gateways in the middle.

**Comment by jamesagnew** [comment]
Hi @dionmcm , @bdenton ,

This issue is actually already fixed- but only in the 1.3-SNAPSHOT build. Someone else discovered it as a part of Argonauts testing about two weeks ago. You can see this in the request headers on a [request on our demo site](http://fhirtest.uhn.ca/search?serverId=home_dev&resource=Patient&param.0.qualifier=&param.0.0=&param.0.name=_content&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=)

And yup, we also accept `application/xml` and `application/json` and treat them the same way as the equivalent correct FHIR types. That part has been in more or less from the start. Thinking about this, we don't accept the text equivalents `text/xml` or `text/json`. I suppose we probably should just to be complete.

**Comment by dionmcm** [comment]
Thanks for responding so quickly @jamesagnew, great that it was already spotted and fixed.

@bdenton I agree that clients should probably be lenient and handle application/xml and application/json without the +fhir part.
