### ISSUE TITLE
(hl7org) JsonParser does not implement IParser interface

### ISSUE THREAD

**Issue by lawley** [jamesagnew/hapi-fhir#260]
The class org.hl7.fhir.instance.formats.JsonParser in hapi-fhir-structures-hl7org-dstu2 is not compatible with the "real" reference implementation version since it does not implement the interface org.hl7.fhir.instance.formats.IParser

**Comment by jamesagnew** [comment]
Hi Michael,

We haven't spent any time getting the RI parser to work in HAPI because HAPI's parser already does this job. Is there some functionality in the RI parser that's missing in HAPI?

(I am aware of JSON comments not being round-tripped correctly yet in HAPI's parser.. I think that's the only different I'm aware of though)
