### ISSUE TITLE
Validation button inactive after reversing out of validation

### ISSUE THREAD

**Issue by ekivemark** [jamesagnew/hapi-fhir#280]
This was done using Safari on OS X.

Choose a Resource.
Choose CRUD Operations
Paste code into Validation section and click Validate Button
If code block fails to validate hit back button to return to previous page. The Validation Button is shaded out and has "Loading" spinner that never clears. The only option is to reload the page and navigate back to CRUD Operations.

**Comment by jamesagnew** [comment]
This has long affected Firefox, I didn't know it also affected Safari. Ugh. Well, thanks for letting us know. :)

The issue is with Bootstrap's `data-loading-text` attribute, which I notice has now been deprecated. Probably because of these issues. I'm going to check in a fix to remove the use of data-loading-text, which will stop buttons from showing the loading spinner when they are clicked but also solved this annoying issue.
