### ISSUE TITLE
Resource Chain not working as documented

### ISSUE THREAD

**Issue by lcamilo15** [jamesagnew/hapi-fhir#286]
I'm trying to follow your Dynamic Chains example and I'm noticing it is not updating the Overlay/GUI documentation as it does for Encounter->Patient chain. Can you please point me in the right direction so that I can implement this right or help you fixing the issue inside of the project?

This is what we are trying to accomplish
![Production encounter chain](http://i.imgur.com/kswQe1F.png)

This is how it is being rendered on our local environment
![Localhost encounter chain](http://i.imgur.com/cIuYAms.png)

```java
@Search()
    public List<Encounter> findEncounter(
        @RequiredParam(name = Encounter.SP_PATIENT,
            chainWhitelist = {Patient.SP_FAMILY, Patient.SP_GENDER})
        ReferenceParam theSubject)
{
...
 }
```

Additional Notes : We are using version 1.3

**Comment by jamesagnew** [comment]
Hi @lcamilo15 - The issue here is definitely that the chains are not being added to the automatically generated conformance statement for your server. I'd say this is an issue with HAPI and not an issue with your code.

The JPA server does add these chains, which is why this works the way you're expecting on our public server. You can see this by looking at the [conformance statement](http://fhirtest.uhn.ca/conformance?serverId=home_dev) for our public server. (search for "chain")

The conformance statement is generated by [ServerConformanceProvider](https://github.com/jamesagnew/hapi-fhir/blob/1ba03f4a9b445c198ca67cd71716ff5a92ffc912/hapi-fhir-structures-dstu2/src/main/java/ca/uhn/fhir/rest/server/provider/dstu2/ServerConformanceProvider.java).

The JPA module [extends that class](https://github.com/jamesagnew/hapi-fhir/blob/479da24cfbb3170c29b1a63fc5af45a5741efeab/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/JpaConformanceProviderDstu2.java) and adds a few things. One of those things is that chains.

I thing these should be added by ServerConformanceProvider.

Are you interested in taking a crack at this bug? If so, awesome! If not, I'll have a look soon.

**Comment by jamesagnew** [comment]
Ok, I actually found some time to work on this and I'm committing a fix now.
