### ISSUE TITLE
Performance Testing issue with HAPI FHIR (JPA Server) Version 1.3

### ISSUE THREAD

**Issue by ashwinigps24** [jamesagnew/hapi-fhir#310]
Hi James,

As requested by you, I am logging a defect in reference to my mail posted on HAPI FHIR Group:-

https://groups.google.com/forum/#!topic/hapi-fhir/_iVsYDvJvno

We did the load testing on Amazon AWS with configuration m4.large (6.5 ECUs, 2 vCPUs, 2.4 GHz, Intel Xeon E5-2676v3, 8 GiB memory, EBS only) and we got the same issue. For your reference we are attaching the Error snapshots and the execution results. Also we found that Update and Delete is very slow compared to insert.

We have been facing a lot of issue while doing performance testing of HAPI FHIR jpa server. We tested below scenarios:-

1) Create of Patient, Practitioner and Observation as bundle insert with 50 concurrent users with 1 sec delay for 10 mins in JMeter
           - Inserted 19,725 Records so total (19,725 \* 3 Resources = 59,175 resources)
           - Average Response time was 0.51 secs
           - 90th Percentile - 0.68 secs
           - 100% successful transactions
           - CPU usage was touching 100% most of the time 

2) Update of Patient, Practitioner and Observation as bundle update with 50 concurrent users with 1 sec delay for 10 mins in JMeter
           - Updated 2949 Records out of 19,725 records that were inserted so total (2949 \* 3   Resources = 8847 resources)
           - Average Response time was 9.16 secs
           - 90th Percentile - 9.61 secs
           - 100% successful transactions
           - CPU usage was 100% all the time 

3) Delete of Patient, Practitioner and Observation as bundle update with 50 concurrent users with 1 sec delay for 10 mins in JMeter
           - Deleted 3483 Records out of 19,725 records that were inserted so total (3483 \* 3   Resources = 10449 resources)
           - Average Response time was 7.56 secs
           - 90th Percentile - 8.47 secs
           - 100% successful transactions
           - CPU usage was 100% all the time

4) While performing the Search operation to pull records of Patient, Practitioner and Observation Resources, the server starts throwing Database Exception after fetching 32000 records.

PFA for your reference.

Regards,
Ashwini

[Error.zip](https://github.com/jamesagnew/hapi-fhir/files/156306/Error.zip)
[HAPI FHIR.zip](https://github.com/jamesagnew/hapi-fhir/files/156305/HAPI.FHIR.zip)

**Comment by RingOfStorms** [comment]
I haven't been able to deep dive look into it, but I am also having issues with reads on HAPI. We have two instances on a load balancer and can really easily break both of them just by throwing a handful of requests at the same time.

For example, I have some code that calls ValueSet expansion on about 50 valuesets. I have to specifically rate limit my code to call them in sequence rather than threaded because the fhir server will immediately just give up on the requests when they are all sent at once. I get not useful logs and my request just ends up timing out. Then it takes about 15 minutes for hapi to respond to any request again (they just timeout with no useful logs).

I haven't run it in debug mode to try and figure out more specifically, but this happens with all sorts of reads for us, not just valueset expansion. Just clicking around in a UI we've built that queries resources by id/params etc has caused the same lock up. Scale is starting to worry me a lot about the hapi server and I don't want to have to implement a rate limit on fhir calls in every application we make.

I'll try to revist this when I can to get better info, but wanted to express my problems quickly here as well.

**Comment by jamesagnew** [comment]
Any thread dumps you can supply for a server in a degraded state would be particularly useful.

A fair bit of performance optimization has gone in in the last few months so that would help to understand what still needs to be optimized.
