### ISSUE TITLE
DateParam from hapi-fhir-base still yields DSTU1 QuantityCompararatorEnum

### ISSUE THREAD

**Issue by Ricq** [jamesagnew/hapi-fhir#323]
When parsing search parameters for dates, the `DateParam` class (which resides in hapi-fhir-base) still uses the DSTU1 `ca.uhn.fhir.model.dstu.valuesetQuantityCompara`**ra**`torEnum`.

When using the DSTU2 implementation, I would expect the DateParam to yield the new `ca.uhn.fhir.model.dstu2.valuesetQuantityComparatorEnum`.

This probably means there need to be two implementations of DateParam (one for DSTU1 and one for DSTU2).

_Note: I have submittted another issue (#324) dealing with the fact that the DSTU2 enum still uses the `=>` and `=<` prefixes, while DSTU2 changed these to `=ge` and `=le`_

**Comment by jamesagnew** [comment]
Hi Rick- This is actually fixed in HAPI FHIR 1.5, which will be released soon. In the [latest version of the code](https://github.com/jamesagnew/hapi-fhir/blob/8de41ca8b4bbae0b3e947bf1a3b5c105dc5d79ac/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/DateParam.java), QuantityCompararatorEnum has been deprocated in favour of a version agnostic [ParamPrefixEnum](https://github.com/jamesagnew/hapi-fhir/blob/8de41ca8b4bbae0b3e947bf1a3b5c105dc5d79ac/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/param/ParamPrefixEnum.java) which uses the old comparators in DSTU1 mode and the new ones in DSTU2/3 modes.

**Comment by Ricq** [comment]
OK. Thanks. We'll wait for that. Hope this also applies to the #324.

**Comment by jamesagnew** [comment]
Hope it helps! I'm going to close this, but please feel free to reopen if the 1.5 fix doesn't solve the issue for you.
