### ISSUE TITLE
HAPI 1.4 Scheduler threads

### ISSUE THREAD

**Issue by mojitoj** [jamesagnew/hapi-fhir#332]
I have been trying to deploy HAPI 1.4 in tomcat. Among other issues and exceptions, I noticed that Tomcat keeps running memory after shutdown throwing a lot of exceptions similar to the following:

org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [hapi14] appears to have started a thread named [Hibernate Search sync consumer thread for index ca.uhn.fhir.jpa.entity.ResourceIndexedSearchParamString] but has failed to stop it. This is very likely to create a memory leak. 

followed by:

org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.hibernate.engine.spi.SessionOwner]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

I have attached the full stack traces of from the catlina.out
[catalina.out.txt](https://github.com/jamesagnew/hapi-fhir/files/208714/catalina.out.txt)
.

**Comment by mochaholic** [comment]
After further investigation, this seems to happen only when fhir.baseurl.dstu* is not defined. 
Is it possible to add some defaults for these variables to avoid this terrifying fail?

**Comment by jamesagnew** [comment]
Well that's.... weird....

I'm assuming you're deploying the `uhn-fhir-jpaserver-uhnfhirtest` WAR file? Which version of Tomcat are you deploying to? Have you made any modifications?

I've actually never managed to get that one project to be able to undeploy and then redeploy on a running Tomcat instance because of Derby's network server, which doesn't seem to be willing to start on a JVM where it's previously been stopped. I've never invested much time on that though since that isn't a production grade solution anyhow- we don't have similar issues when we deploy against Postgres for instance.

**Comment by mochaholic** [comment]
I tried both tomcat 7 and 8 and this is all with Java 1.8. Also, this happens both with the latest snapshot and the 1.4 tag and I have been using MySQL.
I suspect what happens is that after these threads are started, further down the road the web application stops due to exceptions because of the missing properties without cleaning up those threads and that causes tomcat to stay in memory waiting on those threads.
Looking for a solution I found this: https://dzone.com/articles/tomcats-graceful-shutdown

**Comment by jamesagnew** [comment]
Weirdly this doesn't happen for me on the same version of Tomcat as you (although on Mac instead of Linux.

I did possibly track down one of my Derby issues so I fixed that though. I'm not really sure what's the right fix here- those system properties are mandatory and I don't think it would make much sense to include defaults because the server won't work unless it has directories to put the various DBs in and assuming a location is just asking for trouble... Maybe this just needs better documentation..
