### ISSUE TITLE
ID must not be supplied on a create

### ISSUE THREAD

**Issue by forrest23** [jamesagnew/hapi-fhir#333]
I try to create a patient with ID use fhir-net-api. 
` var client = new FhirClient(url);
   Patient patient = new Patient();
   patient.Id = `"0068431";``
It return a error 'ID must not be supplied on a create'.
How can i create  patient with a ID?

**Comment by jamesagnew** [comment]
Hi there,

If you want to supply the ID, you need to use a FHIR update operation (HTTP
put) instead of create (HTTP post) even if the resource doesn't already
exist. This is fhir's rule.

Our server also has a rule that you can only do this for ids that have at
least one letter. Pure numeric ids are reserved for assignment by the
server itself. This is HAPI's rule and doesn't neccesarily apply to other
servers.

Cheers, James.

sent from my phone.

**Comment by forrest23** [comment]
Thanks James! I can create patient with a ID !
`
var client = new FhirClient(url);
Patient patient = new Patient();
patient.Id = "abc";
client.Update<Patient>(patient);
`
