### ISSUE TITLE
updates don't populate Last-Modified or ETag HTTP response headers

### ISSUE THREAD

**Issue by jimsteel** [jamesagnew/hapi-fhir#374]
A successful update (PUT) of a resource should populate the Last-Modified and ETag response headers. From

From https://www.hl7.org/fhir/http.html#update
```If the interaction is successful, the server SHALL return either a 200 OK HTTP status code if the resource was updated, or a 201 Created status code if the resource was created, with a Last-Modified header, and an ETag header which contains the new versionId of the resource. ```

These aren't currently populated.

**Comment by jamesagnew** [comment]
Well... this turned out to be a surprisingly big change. It turns out that create/update/delete use a different code path for responses from read/search/etc. That has been cleaned up so that they both follow the same path. This is definitely an improvement.

Thanks for reporting, checking in a fix shortly!

**Comment by jimsteel** [comment]
I'm seeing the ETag now, but not the Last-Modified. Is there something I need to configure?

**Comment by dionmcm** [comment]
@jamesagnew, just following up on this - should this be producing Last-Modified as well as ETag headers?
