### ISSUE TITLE
(DSTU) Language field cardinality is marked as being (0..*) when it's actually (0..1)

### ISSUE THREAD

**Issue by pramoses** [jamesagnew/hapi-fhir#375]
The language field in the BaseResource for HAPI's DSTU and DSTU2 classes are marked as having a (0..*) cardinality when [FHIR](https://www.hl7.org/fhir/resource-definitions.html#Resource.language) marks it as a (0..1) cardinality.
See
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu/src/main/java/ca/uhn/fhir/model/dstu/resource/BaseResource.java#L87

**Comment by jamesagnew** [comment]
Hi Pramoses,

Thanks for reporting! Oddly enough, even though this issue has existed for quite some time now, this actually got fixed in DSTU2 about 3 days ago: https://github.com/jamesagnew/hapi-fhir/commit/77a84195f57b0c0753f269d3dd5e95737568997b

Looks like we missed the DSTU1 resource. Will commit that now. Thanks again for the heads up!
