### ISSUE TITLE
Invalid date parses as valid date

### ISSUE THREAD

**Issue by cjlint** [jamesagnew/hapi-fhir#381]
See the following code block:

```
import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.model.dstu2.resource.Patient;
import ca.uhn.fhir.parser.IParser;

public class DateParsingError {
    public static void main(String[] args) {
        IParser parser = FhirContext.forDstu2().newJsonParser();
        String jsonPatient =
                "{\"resourceType\": \"Patient\", \"birthDate\": \"9999-99-99\"}";
        Patient p = parser.parseResource(Patient.class, jsonPatient);

        // prints "Thu Jun 07 00:00:00 EDT 10007"
        System.out.println(p.getBirthDate());
    }
}
```

The invalid date 9999-99-99 gets parsed as a valid date, "Thu Jun 07 00:00:00 EDT 10007". It seems that this was supposed to be fixed in issue #50 

EDIT: This is what's in my pom.xml:
```
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-base</artifactId>
            <version>1.5</version>
        </dependency>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-structures-dstu2</artifactId>
            <version>1.5</version>
        </dependency>
```

**Comment by ipropper** [comment]
I believe this is a general problem with HAPI-FHIR not using the java 8 localDate. If the API used the java 8 implementation of date I believe these problems, and several other date issues, would go away.

**Comment by jamesagnew** [comment]
Unfortunately LocalDate isn't an option given our desire to be compatible with older JVMs. As of last year's user survey we still had (iirc) at least 30% of our users on JDK6, so 8 is probably a long way off.

My takeaway from this is that we need to manually parse date/times. It seems like the libraries (either SimpleDateFormat or FastDateFormat) just don't provide the kind of validation we need here.

I've started work on a manual parser to replace the off the shelf parser. I have something basically working now, just cleaning up the kinks...

**Comment by ipropper** [comment]
Could you use joda time? Rolling your own date parser is a massive project on its own.

**Comment by cjlint** [comment]
SimpleDateParser's `setLenient(false)` may also be enough

**Comment by jamesagnew** [comment]
So at this point I've actually got the hand rolled date parser done. I'm going to push it soon- still need to write some more tests.

In the end I actually concluded that this is actually a much cleaner thing than using any of the 3rd party libraries I've looked at. Given the fact that FHIR's spec allows quite a few levels of precision, the code required to use `(Fast | Simple)DateParser` actually involved creating a whole bunch of parser formats for the various levels of precision which was messy. The custom parser actually ends up being fewer lines of code. As a bonus to that, we can fully validate the input, and we now support greater than millisecond precision which isn't possible with any of the date parsers I looked at (but is possible with FHIR's date format).

**Comment by nickbabcock** [comment]
> we now support greater than millisecond precision

That's a nice feature! But I'm curious if this will mean a custom `Date` type because [`util.Date`](https://docs.oracle.com/javase/8/docs/api/java/util/Date.html) only supports millisecond precision (while java8's [`time.LocalDateTime`](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html) supports nanoseconds, and yes I realize java8 isn't an option)

**Comment by jamesagnew** [comment]
I figure the best thing to do is leave Date as the native type, but add an additional method to `BaseDateTimeDt` that lets you access the extra precision if you need to.

To like if you parse `2000-01-01T12:00:44.123456789` you'd still get a `Date` that contains the 123ms but you could also call `getFractionalSeconds()` or something to get the extra precision if you need it.

Thoughts? For that matter, any opinions on what to call the `getFractionalSeconds() method, and what it should return? Internally I'm just storing the fraction as a `long` right now until settling this, but maybe a BigDecimal would make more sense?

So like perhaps it would be called `BigDecimal getFractionalSeconds()` and if you called it for the example above it would return `0.123456789`. Or should it return `44.123456789`? And is that the right name?

**Comment by am202** [comment]
Would it make sense to follow the java.sql.Timestamp example for dealing with fractional seconds?

> int getNanos()
> Gets this Timestamp object's nanos value.

**Comment by nickbabcock** [comment]
Some thoughts:

1. If fhir dates aren't already ISO 8601, switching should be considered -- else the stating ISO 8601 compliance should be added to the docs, complementing the regex already there.

2. Nanosecond precision is as granular as one should go. All libraries that I know of that support ISO 8601 and it's arbitrarily precise format don't support the "arbitrary" part, instead opting usually for nanosecond granularity. Thus, creating an arbitrarily precise date class would only hurt interoperability as too many home grown solutions of questionable quality will appear across systems to satisfy the requirement or they'll truncate the data.

3. Consider using the ThreeTen library. It supports Java 6, nanosecond granularity, and ability to parse strings in multiple formats. Precision can be determined based on the parser that succeeds.

4. If one's still stuck on using `util.Date` and building a custom parser for multiple formats, then at least have `int nanoseconds` since the last millisecond so there is no data overlap between `util.Date` and nanoseconds, as `util.Date` has a millisecond field (ie, you don't want a fractional seconds field, you want fractional milliseconds).

**Comment by jamesagnew** [comment]
> If fhir dates aren't already ISO 8601, switching should be considered -- else the stating ISO 8601 compliance should be added to the docs, complementing the regex already there.

FHIR is fully compliant to 8601 as far as I can see. The issue here is that the Java parsers seem to be remarkably lenient, even when they are configured not to be.

> Nanosecond precision is as granular as one should go. All libraries that I know of that support ISO 8601 and it's arbitrarily precise format don't support the "arbitrary" part, instead opting usually for nanosecond granularity. Thus, creating an arbitrarily precise date class would only hurt interoperability as too many home grown solutions of questionable quality will appear across systems to satisfy the requirement or they'll truncate the data.

This makes sense to me. I'm going to add get/setMillis() and get/setNanos() in order to allow people to interact with either level of precision.

> Consider using the ThreeTen library. It supports Java 6, nanosecond granularity, and ability to parse strings in multiple formats. Precision can be determined based on the parser that succeeds.

Neat. I've never seen this lib. Unfortunately it looks like they have backported to JDK 7, but not 6, so it's probably not an option for us.

**Comment by nickbabcock** [comment]
> Neat. I've never seen this lib. Unfortunately it looks like they have backported to JDK 7, but not 6, so it's probably not an option for us.

Says right on their [github page](https://github.com/ThreeTen/threetenbp) that (emphasis mine):

> JSR-310 provides a new date and time library for Java SE 8. This project is the backport to *Java SE 6* and 7.

:smile:

**Comment by jamesagnew** [comment]
Lol, oops.. how on earth did I misread that?

Ah well- at this point the hand written parser is done, and it seems to work well so I think I prefer that option over adding dependencies anyway. The nice thing is that this parser only actually needs to handle a single format as opposed to being general purpose, so we get a nice performance boost and the ability to emit more tailored error messages.

Using the new parser:
> Parsed 10000 in 382ms - 0.0382ms / pass
> Encoded 10000 in 128ms - 0.0128ms / pass

Using the old parser (FastDateFormat):
> Parsed 10000 in 996ms - 0.0996ms / pass
> Encoded 10000 in 389ms - 0.0389ms / pass

**Comment by nickbabcock** [comment]
Sounds good, thanks for doing the benchmarking

**Comment by jamesagnew** [comment]
Alright, this has finally been fully committed, fully tested, and synced into the DSTU3 structures as well.

Closing it. Woohoo!
