### ISSUE TITLE
Make parts of FhirContext serializable

### ISSUE THREAD

**Issue by Jaypeg85** [jamesagnew/hapi-fhir#383]
Would it be possible to make the reflection heavy parts of FhirContext serializable? This could be helpful for performance on low powered android devices. The serializable parts could then be persisted  when initialized and then read whenever the client is started. 

From what I've looked into, it would involve making BaseRuntimeElementDefinition serializable and parsing the FhirContext a lot more around, and removing it as a private member on the definitions. 
The constructor map on BaseRuntimeElementDefinition could be transient, as it's lazy loaded anyways. The use of Field on runtime definitions could be substituted with field name and a class and made lazy loaded and transient as well.

I don't know if parsing the FhirContext around more within these classes is an option? But shouldn't the callers context be used instead of the context the definition was initialized by?

Regards,
Jeppe

**Comment by Jaypeg85** [comment]
Hi @jamesagnew,

Have you had a chance to look into this?

**Comment by jamesagnew** [comment]
Unfortunately no, not yet. We would welcome pull requests if anyone wanted to try things out though.

I do question how much this would help on Android- the slow part of initializing the context is the model scanning using reflection, and the outcome of that wouldn't be serializable anyhow. We have done a lot of work in 1.6 (which is being released now) to reduce the amount of reflection that is done on startup so this should speed up start times on Android fairly noticeably anyhow. It might be worth trying your application with 1.6 to see if you see enough performance increase to still want to pursue this change.

**Comment by Jaypeg85** [comment]
I have tried the 1.6 snapshots, and it is indeed faster, however it's still not fast. We use the $everything-operation at login, which means a lot models are scanned. And when just ~10 models are scanned at the same time there is a lot of delay.

I started working on this, however when I began parsing the FhirContext around to a lot of methods on the definitions the question about if this was ok or actually just the correct way of doing it popped up. 

For instance toProfile on RuntimeResourceDefinition uses the FhirContext, for instance a DSTU2, that was used for init. But if I call this method from another FhirContext, for instance DSTU1, shouldn't we have used that instead? In this case I would generate a profile using DSTU2, even though my context is DSTU1. And then some of the methods, like sealAndInitialize takes a FhirContext, so that's caller dependant. I guess I'm just not quite sure, which is correct and what's possible.

Also I couldn't figure out what in the FhirContext was created by the model scanner. I figured these:
`    private volatile Map<Class<? extends IBase>, BaseRuntimeElementDefinition<?>> myClassToElementDefinition;
    private Map<String, Class<? extends IBaseResource>> myDefaultTypeForProfile;
    private volatile Map<String, RuntimeResourceDefinition> myIdToResourceDefinition;
    private volatile Map<String, BaseRuntimeElementDefinition<?>> myNameToElementDefinition;
    private volatile Map<String, RuntimeResourceDefinition> myNameToResourceDefinition;
    private volatile Map<String, Class<? extends IBaseResource>> myNameToResourceType;
private volatile RuntimeChildUndeclaredExtensionDefinition myRuntimeChildUndeclaredExtensionDefinition;
 private Map<FhirVersionEnum, Map<String, Class<? extends IBaseResource>>> myVersionToNameToResourceType;`

**Comment by jamesagnew** [comment]
Yeah, all of those are.. And I guess that's part of the problem here, those are the things that are expensive to create, and they won't serialize anyhow since they require reflection in order to set up.

I'm not sure I follow the DSTU1/2 stuff though.. Are you trying to write an app that will talk to both a DSTU1 and a DSTU2 server from the same running app instance? There isn't much opportunity for efficiency across two contexts for different versions since they will (by design) need to reflect on completely different models.

Now that 1.6 is live and I can point to its docs, have you tried the [deferred model scanning](http://hapifhir.io/doc_rest_client_http_config.html#performance) mode that was added in 1.6?

Finally, how long are we talking, and on what kind of phone? It might be worth running a profile similar to what was done in [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hapi-fhir/75mDDTkozpI/0BP_c6nDAwAJ) to see if you can nail down exactly what part of the initialization is taking so long... maybe that would help to point to what needs optimization
