### ISSUE TITLE
contained Resources not populated in getServerConformance call

### ISSUE THREAD

**Issue by lawley** [jamesagnew/hapi-fhir#395]
When overriding ServerConformanceProvider.getServerConformance to tailor the Conformance resource, the instance returned by calling super.getServerConformance doesn't yet have the contained Resources (OperationDefinitions) populated.

This means we can't correct/modify them or remove them.

**Comment by jamesagnew** [comment]
Is this against 1.5, or the latest 1.6-SNAPSHOT builds?

The conformance generated in 1.6 is still definitely not perfect, but one change that is in there since 1.5 is that we did away with using the contained resources for OperationDefinitions. The root cause of your issue isn't yet fixed, but possibly working around it might be easier.. :)

**Comment by lawley** [comment]
Hmm, this is against latest 1.6-SNAPSHOT.

**Comment by jamesagnew** [comment]
Hmm, I wonder if there is any chance this was fixed since the last time I pushed a snapshot. It probably was actually.

I just pushed a new 1.6-SNAPSHOT build to Maven, do you mind to try again? Our [public server](http://fhirtest.uhn.ca/baseDstu3/metadata) isn't showing the contained operation definitions so I know this is working somehow. :)

**Comment by lawley** [comment]
Excellent, looks like we're getting closer.  Just got the latest build and indeed there are no contained `OperationDefinition`s now.  The relative links resolve which is also good.

However, the metadata also lists `StructureDefinition` as a supported resource for read and search-type.  When I do a search I get one match for `[base]/StructureDefinition/operationdefinition` but that returns on `OperationOutcome` with "Resource StructureDefinition/operationdefinition is not known".

Trying `StructureDefinition` on your public server gives an internal error "Failed to call access method"
