### ISSUE TITLE
Paging to last page returns incorrect subset

### ISSUE THREAD

**Issue by cknaap** [jamesagnew/hapi-fhir#397]
The last result of the previous page is repeated, and the last result of the search set is not included.
I guess the calculation of the offset is incorrect, but the count is correct.

Example: Observation?patient=ZD-ex-1
13 results, 10 per page
last result on page 1 is Observation/111226
first result on page 2 is also Observation/111226
other results on page 2 are 111228 and 11229

If you search again with _count=20, Observation/111230 is also included

**Comment by rdsteed** [comment]
I've been observing the same behavior.  When paging is used, the last page in a multi-page fetch overlaps the previous page and is missing the last values on the last page.

I believe this may be due to a problem in the routine from 
hapi-fhir/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/SearchCoordinatorSvcImpl.java:

	static Pageable toPage(final int theFromIndex, int theToIndex) {
		int pageSize = theToIndex - theFromIndex;
		if (pageSize < 1) {
			return null;
		}

		int pageIndex = theFromIndex / pageSize;

		Pageable page = new PageRequest(pageIndex, pageSize) {
			private static final long serialVersionUID = 1L;

			@Override
			public int getOffset() {
				return theFromIndex;
			}
		};

		return page;
	}

If theFromIndex is not an integer multiple of pageSize, this problem occurs.
