### ISSUE TITLE
Unknown request parameters are handled badly

### ISSUE THREAD

**Issue by jkiddo** [jamesagnew/hapi-fhir#405]
The HAPI server does not like unknown request parameters, eg: http://fhirtest.uhn.ca/baseDstu3/Patient?name=John&unknownRequestParameter=v

The error message from executing the above HTTP request as GET results in the following message in the diagnose field: "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient] with parameters [[unknownRequestParameter, name]]"

While this may be true its not that helpful. Either the server should ignore the parameter as most web servers would do or the server should helpfully tell what parameters actually are supported listing what is required and what is optional

**Comment by jkiddo** [comment]
This is also in line with http://hl7-fhir.github.io/search.html#errors

**Comment by jkiddo** [comment]
@drewctaylorgtri so I found out. The issue is 7 years old

**Comment by drewctaylorgtri** [comment]
Yes, it's old. But it's new to me, and I imagine it will be new to future developers. Since it hasn't made its way into the HAPI FHIR documentation yet, I thought it would be helpful to them to put a solution in a prominent place (this is the first result when you search "hapi fhir unknown parameter").

**Comment by jkiddo** [comment]
I just stumbed upon this again 😆 - but this time, past-me saved future-me 🤣
