### ISSUE TITLE
inconsistent behavior between a IGenericClient.create() and a raw post. 

### ISSUE THREAD

**Issue by evanderzwan** [jamesagnew/hapi-fhir#418]
During a test  I am trying to create a resource which includes an id. This is not allowed. The resource:

```
<Encounter xmlns="http://hl7.org/fhir"> 
    <id value="123"/>
</Encounter>
```

Posting this to a testserver (or your own hapi server) it will get you:
_Error: HTTP 400 Bad Request: Can not create resource with ID "123", an ID element must not be supplied in the resource body on a create (POST) operation_
Which is the response expected. 

Then with a client (fhirContext.newRestfulGenericClient) in a unit test.

```
@Test
    public void testCreate_With_Illigal_Id_In_Resource() {
        Encounter encounter = new Encounter();
        IdType id = new IdType();
        id.setValue("123");
        encounter.setIdElement(id);
        MethodOutcome outcome = client
                .create()
                .resource(encounter)
                .prefer(PreferReturnEnum.REPRESENTATION)
                .execute();
        if (outcome.getCreated() != null) {
            fail();
        }
    }
```

When run the id is stripped before it is send to the server. The server response with a http 201, and created an empty encounter without the given id (and generated a new one)

The hapi client should throw an exception before sending it to the server (not to bother the server) or leave the faulty id intact so the server can respond to it with a http 400.

**Comment by jamesagnew** [comment]
This behaviour is intentional. It's certainly debatable if it's right, but at least it's deliberate. :)

HAPI's client ignores the resource's ID when performing a create as a way of being helpful. At least personally, I often want to create resources using cut-and-paste examples, so having the client ignore any ID that might be present is useful. 

I guess the counter-argument here is that a client trying to do a create with an ID might actually think they are doing something they aren't actually allowed to do, so HAPI is being misleading?

**Comment by jimsteel** [comment]
@jamesagnew Has the server-side behaviour for POSTs containing IDs been changed? I'm seeing 201s now (2.1-SNAPSHOT) where I used to see 400s, even when using a straight HTTP client. I'm also seeing this for PUTs where the URL/Resource IDs differ, which may or may not be related.
