### ISSUE TITLE
javax.net.ssl.SSLHandshakeException (Fhir client)

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#420]
Hello,

   When I use the fhir client to invoke the fhir API (URL), it reports an error about the javax.net.ssl.SSLHandshakeException.  In our system, we will enable the SSL to invoke each restful APIs. Is there any way to resolve this issue? 

ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:249)
 at ca.uhn.fhir.rest.client.GenericClient$BaseClientExecutable.invoke

**Comment by baopingle** [comment]
Andy idea about it.  Seek help

**Comment by jamesagnew** [comment]
Hi @baopingle , this isn't a HAPI specific issue, but rather Java is unable to successfully make an HTTPS connection to your server.

Unfortunately there are many reasons why this could be happening, and they are often hard to track down. Your server may have a misconfigured or expired certificate, you client may not have the necessary chain of trust or root certificates configured, the server may have TLS client authentication enabled, etc. 

I would recommend making sure you are using the very latest JDK release (since sometimes older JDKs are missing newer Root CA certificates) and trying the URL of your FHIR server in a browser to see if the browser is able to negotiate an encrypted connection. Failing that, you may want to try googling the non-FHIR parts of the stack trace, there are good resources on the internet about how to diagnose `SSLHandshakeException` but this is certainly beyond the scope of HAPI.
