### ISSUE TITLE
Thymeleaf tags are not interpreted inside script tags

### ISSUE THREAD

**Issue by Robbert1** [jamesagnew/hapi-fhir#431]
When trying to run the jpaserver-example from the master branch I get javascript errors in the frontend. These seem to be caused by blocks like "<th:block th:utext="${jsonEncodedConf}"/>" are send unparsed to the client.

I think this is the result of the upgrade to thymeleaf 3?

**Comment by jamesagnew** [comment]
Thanks for reporting! 

This was indeed a regression caused by the upgrade to Thymeleaf 3. Man, what a pain in the butt that was to fix. The Thymeleaf author claimed that the upgrade shouldn't affect templates, but it actually caused all kinds of issues.

They've been ironed out now, thankfully. Will commit a fix shortly.

**Comment by jamesagnew** [comment]
Ps- If you could test and confirm it's fixed for you too I'd appreciate that :)

**Comment by Robbert1** [comment]
Wow... big fix indeed. 

Everything seems to be working now (when running on locally installed snapshot of the overlay.)
