### ISSUE TITLE
No longer producing Location HTTP Response header

### ISSUE THREAD

**Issue by jimsteel** [jamesagnew/hapi-fhir#472]
I've noticed that since switching to 2.1-SNAPSHOT, PUT/POST requests are no longer producing the Location header (the Content-Location header is still there, though, with the same value). Is this intended?

**Comment by jamesagnew** [comment]
Oops! Early in the DSTU3 development process we decided to get rid of one of the two headers since they were redundant.

Possibly I'm remembering this part wrong but I think we picked for `Content-Location` to be the one that survived. Either way, it's definitely `Location` now in the [spec](http://hl7-fhir.github.io/http.html#create) so HAPI's doing the wrong thing. 

I'll update.
