### ISSUE TITLE
Failing to retrieve a basic resource after correct creation

### ISSUE THREAD

**Issue by ultrapingu** [jamesagnew/hapi-fhir#484]
I've ran into the following issue which I have also posted about here:

http://stackoverflow.com/questions/40363249/hapi-failing-to-return-basic-resource-after-successful-upload

The ins and outs are that I'm creating an instance of a basic resource which I've uploaded via a batch, on execution the batch returns '201 Created' for the instance along with it's id of 1107.  When I try to return it via the url {{URL}}/Basic/1107 however, I get an error returned with the diagnostic of 'Failed to call access method'.

When I upload the example patients, I can retrieve them as expected so it doesn't appear to be something affecting all resources/instances

**Comment by rqg0717** [comment]
It seems like we are trying to achieve the same task to force the server to use a specific ID. If negetive, then you should not use the id 1107 to search for the new record since every time you create a new instance of a resource, the server will assign a new resource ID for the instance. I hope this would help. Thanks.

**Comment by jamesagnew** [comment]
Hi @ultrapingu - I've had a look and this is a bug in our parser. I'm going to check in a fix shortly. Thanks for reporting!

FYI I'll push a new 2.1-SNAPSHOT build with the fix shortly as well, but you could also work around this by not including the empty `<div/>` in your narrative. The bug here is that HAPI isn't correctly parsing that.
