### ISSUE TITLE
Can't build hapi-fhir-jpaserver-example

### ISSUE THREAD

**Issue by codebusta** [jamesagnew/hapi-fhir#522]
The following error is shown when mvn install is run:
[INFO] Compiling 4 source files to D:\Farhod\projects\fhir\hapi-fhir\hapi-fhir-jpaserver-example\target\
classes
D:\Farhod\projects\fhir\hapi-fhir\hapi-fhir-jpaserver-example\src\main\java\ca\uhn\fhir\jpa\demo\JpaServ
erDemo.java:34: error: cannot find symbol
import ca.uhn.fhir.rest.server.interceptor.CorsInterceptor;
                                          ^
  symbol:   class CorsInterceptor
  location: package ca.uhn.fhir.rest.server.interceptor
1 error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.296 s
[INFO] Finished at: 2016-12-01T19:04:49+04:00
[INFO] Final Memory: 39M/326M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-com
pile) on project hapi-fhir-jpaserver-example: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles
:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rluncasu** [comment]
+1, same here

**Comment by jamesagnew** [comment]
Would you be able to try it again?

It looks like the last snapshot didn't upload to maven central. I've fixed
that now.

sent from my phone.

**Comment by jamesagnew** [comment]
Closing, this should be fixed. Please feel free to comment if this is still happening.

**Comment by Nunalves** [comment]
I'm getting the same error message for several Classes upon doing mvn install after a clean clone of the repo:

> [INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ca.uhn.hapi.fhir:hapi-fhir-jpaserver-example:war:2.5-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty.websocket:websocket-api:jar -> version ${jetty_version} vs (?) @ ca.uhn.hapi.fhir:hapi-fhir-jpaserver-example:[unknown-version], /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/pom.xml, line 168, column 15
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty.websocket:websocket-client:jar -> version ${jetty_version} vs (?) @ ca.uhn.hapi.fhir:hapi-fhir-jpaserver-example:[unknown-version], /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/pom.xml, line 173, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building HAPI FHIR JPA Server - Example 2.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ hapi-fhir-jpaserver-example ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java) @ hapi-fhir-jpaserver-example ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hapi-fhir-jpaserver-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ hapi-fhir-jpaserver-example ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[23,34] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu2Interceptor
  location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[24,34] error: cannot find symbol
  symbol:   class WebSocketSubscriptionDstu2Interceptor
  location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[25,35] error: cannot find symbol
  symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu2
  location: package ca.uhn.fhir.jpa.subscription
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[26,27] error: cannot find symbol
  symbol:   class SpringObjectCaster
  location: package ca.uhn.fhir.jpa.util
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[23,34] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu3Interceptor
  location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[24,34] error: cannot find symbol
  symbol:   class WebSocketSubscriptionDstu3Interceptor
  location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[25,35] error: cannot find symbol
  symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu3
  location: package ca.uhn.fhir.jpa.subscription
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[26,27] error: cannot find symbol
  symbol:   class SpringObjectCaster
  location: package ca.uhn.fhir.jpa.util
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[74,43] error: cannot find symbol
  symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu2
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,3] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu2Interceptor
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,107] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu2Interceptor
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,51] error: cannot find symbol
  symbol:   variable SpringObjectCaster
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[209,13] error: cannot find symbol
  symbol:   class WebSocketSubscriptionDstu2Interceptor
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[215,13] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu2Interceptor
  location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[76,75] error: cannot find symbol
  symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu3
  location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[102,13] error: cannot find symbol
  symbol:   class WebSocketSubscriptionDstu3Interceptor
  location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[108,13] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu3Interceptor
  location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,3] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu3Interceptor
  location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,107] error: cannot find symbol
  symbol:   class RestHookSubscriptionDstu3Interceptor
  location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,51] error: cannot find symbol
  symbol:   variable SpringObjectCaster
  location: class FhirServerConfigDstu3WSocket
[INFO] 20 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.458 s
[INFO] Finished at: 2017-05-21T17:08:58+01:00
[INFO] Final Memory: 41M/276M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project hapi-fhir-jpaserver-example: Compilation failure: Compilation failure:
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[23,34] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu2Interceptor
[ERROR] location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[24,34] error: cannot find symbol
[ERROR] symbol:   class WebSocketSubscriptionDstu2Interceptor
[ERROR] location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[25,35] error: cannot find symbol
[ERROR] symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu2
[ERROR] location: package ca.uhn.fhir.jpa.subscription
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[26,27] error: cannot find symbol
[ERROR] symbol:   class SpringObjectCaster
[ERROR] location: package ca.uhn.fhir.jpa.util
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[23,34] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu3Interceptor
[ERROR] location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[24,34] error: cannot find symbol
[ERROR] symbol:   class WebSocketSubscriptionDstu3Interceptor
[ERROR] location: package ca.uhn.fhir.jpa.interceptor
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[25,35] error: cannot find symbol
[ERROR] symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu3
[ERROR] location: package ca.uhn.fhir.jpa.subscription
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[26,27] error: cannot find symbol
[ERROR] symbol:   class SpringObjectCaster
[ERROR] location: package ca.uhn.fhir.jpa.util
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[74,43] error: cannot find symbol
[ERROR] symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu2
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,3] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu2Interceptor
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,107] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu2Interceptor
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[112,51] error: cannot find symbol
[ERROR] symbol:   variable SpringObjectCaster
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[209,13] error: cannot find symbol
[ERROR] symbol:   class WebSocketSubscriptionDstu2Interceptor
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigWSocket.java:[215,13] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu2Interceptor
[ERROR] location: class FhirServerConfigWSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[76,75] error: cannot find symbol
[ERROR] symbol:   class SubscriptionWebsocketReturnResourceHandlerDstu3
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[102,13] error: cannot find symbol
[ERROR] symbol:   class WebSocketSubscriptionDstu3Interceptor
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[108,13] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu3Interceptor
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,3] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu3Interceptor
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,107] error: cannot find symbol
[ERROR] symbol:   class RestHookSubscriptionDstu3Interceptor
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] /home/nuno/Development/GIT/hapi-fhir/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfigDstu3WSocket.java:[139,51] error: cannot find symbol
[ERROR] symbol:   variable SpringObjectCaster
[ERROR] location: class FhirServerConfigDstu3WSocket
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Nunalves** [comment]
Maybe it has to do with the last commit on the hooks implementation

**Comment by Nunalves** [comment]
Ok, this problem definitely started happened after the last jpa-example commit on the hooks implementation: 663125fe94a9c6a173185d59f6de07eb0017e723
Because i checked out the: fa2950dacbd440259b096aed27146240ca3cfb7b and it works fine
@javajeff it would be really nice to have your implementation, i don't know much about maven, but maybe it is the same problem mentioned by @jamesagnew: `It looks like the last snapshot didn't upload to maven central.`

**Comment by jamesagnew** [comment]
There were a few glitches doing the merge, but this should be fixed now with the latest code. Please let me know if you continue to see issues with the build.

**Comment by anandmn86** [comment]
when i am running the command $ mvn install i get the below error. Can someone please help how to fix it?

Could not resolve dependencies for project ca.uhn.hapi.fhir:hapi-fhir-jpaserver-example:war:3.3.0-SNAPSHOT: Failure to find ca.uhn.hapi.fhir:hapi-fhir-jpaserver-elasticsearch:jar:3.3.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-snapshots has elapsed or updates are forced

**Comment by jamesagnew** [comment]
Hi @anandmn86 this ticket is closed. Please see #898
