### ISSUE TITLE
LanientErrorHandler - Found incorrect type for element address - Expected ARRAY and found OBJECT

### ISSUE THREAD

**Issue by volodymyr-vynnytskyi** [jamesagnew/hapi-fhir#564]
Hi,

We are getting above warning while performing some operations with Organization. We have own child resource extended from Organization where bounds for 'address' field have been changed from 0..* to 0..1. So actually in JSON our address field represented as single object, not as array of objects.
In JsonParser class line 1359 code theState.elementIsRepeating(theName) returns true, because for some reason it uses BaseRuntimeChildDefinition where 'address' field bounds are  0..*, however in our case it should be 0..1.
HAPI version is 2.2

**Comment by jamesagnew** [comment]
Is it actually valid to change the seralized form when the cardinality is reduced? I'm not actually clear if the warning is an issue, or if the issue is the fact that this isn't being serialized as an array by the parser.

Asking Zulip for opinions: https://chat.fhir.org/#narrow/stream/implementers/topic/Reducing.20Cardinality.20via.20Profile
