### ISSUE TITLE
DELETE resource (the first time) sometimes returns http status code 200

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#573]
DELETE resource (the first time) sometimes returns http status code 200 as opposed to NoContent (204)
DSTU3
2.3 snapshot

**Comment by jamesagnew** [comment]
Hi @gsureshkumar,

Thanks for the report! Is this against a public server, or a deploy of the jpa server, or something else? What are the steps to reproduce it?

**Comment by gsureshkumar** [comment]
Hi James,

I noticed this with JPA server.
Used jpa-server-example and configured it to connect to sql server instance.
The error was noticed for simple create and delete operation for Patient/ImaginsStudy/Observation/DiagnosticRequests/DiagnosticReports

thanks,
Suresh

**Comment by jamesagnew** [comment]
I'm a a bit confused by this. I ran the jpaserver-example to try this, and it *always* returns a 200, not sometimes.

It does that because it's returning an OperationOutcome describing the response and according to the FHIR specification a 200 is what it should return if the response contains a payload.
