### ISSUE TITLE
org.hl7.fhir.dstu3.model.DomainResource#listChildren() does not contain the super.listChildren() call

### ISSUE THREAD

**Issue by wdaehn** [jamesagnew/hapi-fhir#619]
As a result the "new Patient().children()" method does not return any of: id, meta, implicitRules, language
None of the Resource#listChildren() elements.

DomainResource should rather read:

```
protected void listChildren(List<Property> childrenList) {
  super.listChildren(childrenList);
  ... 
  ...
```

**Comment by jamesagnew** [comment]
FYI that method is not a part of HAPI's suported API. It comes from the RI structures but it does not get used by HAPI's parser and isn't guaranteed to work or continue to exist long term.

If you want a proper listing of child elements you'd need to use HAPI's metamodel via the FhirContext#getResourceDefinition() method.

**Comment by wdaehn** [comment]
Aaargh.   :-)

Relying on this gives you a much cleaner encoder. I have merged the XmlParser and BaseParser into one class and then removed the IParser interface end everything you don't need for creating a record (meaning an ArrayList of columns where sub-structures are nested ArrayLists).

The result of that is working an 60'613 characters of code. That is a lot. Especially as it contains expensive operations like Class.cast() as well. 

In comparison, using the Patient.children() method is 100 lines of code. You simply check if the property has a value, if not skip it. I would think you can speed up the JsonParser/XmlParser significantly by using that.
The reading of json/xml probably as well. 

Am I missing something?

**Comment by jamesagnew** [comment]
The `children()` method is used by the RI parser, and it is indeed cleaner. The problem is that it isn't able to handle a number of scenarios: Using HAPI's annotations it is possible for user code to create resource subclasses that override fields in the base classes to specify custom datatypes or change cardinality, add extension fields, etc. Those changes would not be visible to the parser if it relied purely on `children()`. 

Naturally things ..could.. be shifted so that such structures are required to modify `children()` but we have always opted for a messier parser in exchange for cleaner user code.
