### ISSUE TITLE
DSTU3 IdType.getIdPart() return a string including # 

### ISSUE THREAD

**Issue by JiajingLiang** [jamesagnew/hapi-fhir#635]
In DSTU3, for all Reference and Resource, Reference::getReferenceElement().getIdPart() and Resource::getIdElement().getIdPart() return a string including '#', which is not the case in DSTU2.

**Comment by jamesagnew** [comment]
This was actually a deliberate choice.

It only applies to contained resources, which have an ID like `#30` instead of an ID like `http://base/Patient/30`.

We included the # in order to help clients differentiate between a "local" id of 30 (for a contained resource) vs an actual ID of 30 (for a normal non-contained resource). I feel like not making this distinction explicit would be dangerous.. Do you feel otherwise?

**Comment by jjliang1005** [comment]
Thanks for the explanation. 
Personally, I feel more clear that IdType::getValue() return a id with the # which makes the difference between contained resource and a non-contained resource. The method IdType::isLocal() can also check it. 
Otherwise, it's quite convenient to have a method which returns just the id without any symbol in standard FHIR.
