### ISSUE TITLE
Tinder plugin support for STU3

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#698]
The tinder plugin does not currently process generic Velocity templates for STU3 resources, datatypes, or valuesets. I suspect this is because the JPA server didn't need the support and STU3 resources are not generated in HAPI either.

I have some requirements to generate some non-Java stuff with tinder. Is "real" STU3 support in tinder worth pursuing or has it been attempted and run into issues??

**Comment by jamesagnew** [comment]
It's never been attempted because it's not needed (as of DSTU2.1 we use the official HL7 Spec Build process as our source for structures), but there is no reason it couldn't work.

The tinder plugin does still process DSTU3 (and now 4) spreadsheets to generate resource providers for JPA, so it's at least able to read them.

If you are going to take a crack at this in the short term, I'd highly recommend branching off of the `hapi3_refactor` branch rather than the `master`. This won't be the case for more than a few weeks but it has significant changes from master, and more are coming.

**Comment by bdenton** [comment]
Thanks James... I had been meaning to look over your refactoring branch anyway..

BTW, do you know where I can find compartments.xml for STU3??

**Comment by splatch** [comment]
Are there any plans to solve this issue? I ran into this one due to unsupported valuesets:
https://github.com/jamesagnew/hapi-fhir/blob/e19c13fa6f03f1a84a9ef8c21dbce50a832145dc/hapi-tinder-plugin/src/main/java/ca/uhn/fhir/tinder/ValueSetGenerator.java#L103

I don't try to map value sets itself but rely on DSTU3 resources in order to generate "proxy" code.

**Comment by splatch** [comment]
@jamesagnew could you please share information how to use tinder plugin to generate resource server stubs for STU3?
