### ISSUE TITLE
[Question] Data type choice of Resource Id in JPA server 

### ISSUE THREAD

**Issue by JiajingLiang** [jamesagnew/hapi-fhir#754]
Hello James,
I'd like to ask you a question about data type choice of Resource Id you've made for the JPA server. I've notice that the Ids of all resource are of Long type and generated by a sequence generator, while the id of Bundle is a random UUID. I found that it's a little bit incoherent in my opinion. I'd like to know why the choice is made. 

Thank you very much in advance, and looking forward for explanation.

**Comment by jamesagnew** [comment]
Hi Jiajing,

(Please direct questions to the HAPI FHIR Google Group, not the GitHub
Issue tracker)

Search results are indeed populated with a random UUID currently. This is
very interesting timing though- this has just changed as of GitHub master
about 4 days ago.

As of the latest version, the Bundle ID for a search/history operation will
be set to the UUID assigned to that search (so if a search returns results
from the query cache instead of going back to the database, it'll get the
same bundle ID as the previous search).

Cheers,
James
