### ISSUE TITLE
Release version 3.0 of hapi-fhir-osgi-core

### ISSUE THREAD

**Issue by SarenCurrie** [jamesagnew/hapi-fhir#777]
Is there any reason this was left out when releasing the rest of 3.0?

**Comment by joedai** [comment]
The same wonder here, we are planning to move on to STU3 and the hapi-fhir-osgi-core 3.0.0 is not available.

**Comment by fmayoral** [comment]
I have the same question here, any specific reason why this is not released?

**Comment by jamesagnew** [comment]
I'm actually not sure how this got removed from the build, but it must have been a part of the giant refactor that happened in 3.0.0.

I do believe that it should be possible now to add manifest files to each of the individual HAPI FHIR module JARs now though. This wasn't done originally because of conflicting package names but this should no longer be an issue since we dropped DSTU1 support I believe.

I'm not an OSGi expert though... Can anyone see any reason this wouldn't work?
