### ISSUE TITLE
Missing "total" property in Bundle responses

### ISSUE THREAD

**Issue by vlad-ignatov** [jamesagnew/hapi-fhir#785]
It seems that if we request a resource (without search parameters) we don't get a `total` property. However, if I refresh that page or just repeat the same request one more time, then the `total` property appears. This was observed on HAPI 3.0/DSTU2 and HAPI 3.1/DSTU2. Example -
 http://vpn-172-18-195-159:9080/hapi-fhir-jpaserver-example/baseDstu2/Encounter

I am not sure if this is a bug or some kind of caching improvement but I can imagine many apps breaking due to it.

**Comment by vlad-ignatov** [comment]
Sorry, I meant to give an url from your server like http://fhirtest.uhn.ca/baseDstu3/Observation.

**Comment by jamesagnew** [comment]
Hi @vlad-ignatov - This actually is intended behaviour, and it's related to caching as you suggested. Basically, in order to respond quickly, by default HAPI returns results as soon as it has fetched a page, even if it doesn't yet know the full count. Often if you fetch subsequent pages, it will have the total ready by then so the total starts showing up.

HAPI 3.1.0 (which isn't released yet but does have a snapshot build available on Maven) introduces the [setCountSearchResultsUpTo](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/DaoConfig.java#L182) property, which allows you to tweak this behaviour.

The public server has been configured to show counts for search results up to 50K results.. At this moment, the [all Patients](http://fhirtest.uhn.ca/baseDstu3/Patient) search will always include a count (since it returns 20K results) but the [all Observations](http://fhirtest.uhn.ca/baseDstu3/Observation) search does not as it returns > 100K.
