### ISSUE TITLE
Modular OSGi Support

### ISSUE THREAD

**Issue by fmayoral** [jamesagnew/hapi-fhir#826]
Hello!
We are currently moving towards supporting STU3 on an OSGi environment and after the changes on package names in HAPI we think this is feasible without any need to repackage.
I have noticed hapi-fhir-osgi-core puts everything together but it's not the best approach given that we could have it modular. It is a bit hard to tell what should be put in each manifest but we'll give it a go; However I must ask first, is there any known reason why this wouldn't work or create some issues?
Thanks!

**Comment by johnpoth** [comment]
Hi @fmayoral it seems from #784 that hapi-fhir-osgi-core was created because there were split packages which don't seem to exist anymore.
Are you still having a go at implementing this? I'd be happy to help out.

**Comment by fmayoral** [comment]
I'm at it right now, just for a few bundles I need to have (base, utilities, server, client and dstu3); 
I've mostly used the maven bundle plugin to get it going, with some tweaking here and there; Ideally, I'd go module by module doing this correctly but the work I'm doing with this wouldn't allow it because of time/priorities.

Due to the reflective behaviour of some flows there seem to be some "soft dependency" (not really a dependency but not sure how to call it) from some modules onto others, this is fine when no strict modularity is applied, but the moment I create OSGi manifests I start getting a lot of issues with class resolution as the bundles try to access elements that are not present in the manifest, hence unavailable to them.
For this to work I need to enable the dynamic import package header which defeats the modular nature of OSGi, the alternative is to start working on a different architecture that doesn't rely on reflection (or if it does in a way that doesn't create circular "soft dependencies") to handle these scenarios in an appropriate way;

The ones I've identified so far are:
hapi-fhir-base needs to have access to:
```
// all the contexts
ca.uhn.fhir.model.dstu2;resolution:=optional,
org.hl7.fhir.instance;resolution:=optional,
org.hl7.fhir.dstu2016may.hapi.ctx;resolution:=optional,
org.hl7.fhir.dstu3.hapi.ctx;resolution:=optional,
org.hl7.fhir.r4.hapi.ctx;resolution:=optional,
// required when building servers
ca.uhn.fhir.rest.api.server;resolution:=optional,
ca.uhn.fhir.model.api;resolution:=optional
```
additionally I've enabled dynamic package import package as follows, so there might be more scenarios uncovered by previous imports:
```
<DynamicImport-Package>
ca.uhn.fhir.*;version="3.2.0", 
org.fhir.*;version="3.2.0", 
org.hl7.fhir.*;version="3.2.0"
</DynamicImport-Package>
```
Seems to do the trick, but every once in a while I hit something that's missing and need to go back to check what I need to add, so I wouldn't say I trust what I've got so far.

**Comment by johnpoth** [comment]
@fmayoral great work! Looks like it won't be trivial because fhir-base is using reflection to load other contexts (dtsu2, dtsu3 etc..).

I agree with your comments on using simply `DynamicImport-Package *`. That being said, given the situation, using `ca.uhn.fhir.*` etc.. seems more than reasonable.

**Comment by jamesagnew** [comment]
This is sounding awesome. Please let me know if there is anything that could be changed in the library to make this task easier.

The reflection sort-dependencies are hard to work around since we do want to mantain the ability for the FhirContext to discover available versions and work correctly without all of them present, but there might be mitigations.

E.g. perhaps it might work to have an alternate mechanism for the structures JARs to register with [https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirVersionEnum.java](FhirVersionEnum) via a manual call in client code for OSGi users? I would assume something like that, where hapi-fhir-structures-XXX.jar has a class that can be called to register it with the version class, would turn this into a simple one-way dependency?

**Comment by johnpoth** [comment]
@jamesagnew your suggestion sounds a lot like converting hapi-fhir-structures into OSGI [fragments](https://www.eclipse.org/gemini/blueprint/documentation/reference/2.0.0.RELEASE/html/appendix-tips.html) and hapi-fhir-base would be the host bundle. They would share the same classloader and possibly mitigate some of the classloading issues @fmayoral is encountering?

**Comment by jamesagnew** [comment]
That ..sounds... like the right approach. I have to be clear though that I'm not an OSGi expert by any means. :)

**Comment by fmayoral** [comment]
Using fragments makes sense to me too as that seems to better describe what it does and it'll probably easier to support. Not sure if that was the original intention or if a different pattern would be preferred to allow strict modularity; In any case that'd be a different problem.
I'll be abandoning my current approach, we'll just bundle everything together for now as it's taking me too long to get this running and I'm not confident on how it will hold up moving forward.
I might come back to it later to have a look at fragments.
