### ISSUE TITLE
Performances Suggestion [1]

### ISSUE THREAD

**Issue by parisni** [jamesagnew/hapi-fhir#895]
Hello

The first issue when dealing with large datasets is that the whole both java resultset and Resource object have to fit in memory before being serialized.

Is there a way to stream the result with pagination ?

**Comment by jamesagnew** [comment]
Hi @parisni, you can supply your own implementations of IPagingProvider and IBundleProvider which stream responses if you want to.

The JPA module does exactly this, using its own [paging provider](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/DatabaseBackedPagingProvider.java) and [bundle provider](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/search/PersistedJpaBundleProvider.java)

**Comment by jamesagnew** [comment]
You can return an IResourceProvider with any implementation you want right
from the search() method instead of a List if you want. This is how the JPA
server accomplishes the streaming. E.g. here's an example from the JPA
server:
http://hapifhir.io/xref-jpaserver/ca/uhn/fhir/jpa/rp/dstu2/PatientResourceProvider.html

Cheers,
James

**Comment by parisni** [comment]
That's very interesting for my future improvements. Thanks.
