### ISSUE TITLE
Database migration strategy?

### ISSUE THREAD

**Issue by Romanow88** [jamesagnew/hapi-fhir#971]
Is there a DB migration strategy for FHIR? The last update required a db migration and it would be nice to have either jdbc code or scripts that migrate the DB (configurable or mandatory?).

**Comment by anthonys123** [comment]
I suggest the use of Flyway for the migrations.  Good tool to use.

**Comment by Romanow88** [comment]
We are using flyway internally. I was wondering is something was / will be provided by the implementation or should we do that externally.

**Comment by jamesagnew** [comment]
I would definitely love for this to be something we provide as a part of HAPI FHIR releases. The fact we want it certainly isn't due to lack of interest. :)

@Romanow88 Is your work on Flyway something you might be able to submit back?

I guess more generally, if anyone would like to help out with this task we would greatly appreciate it.

**Comment by Romanow88** [comment]
@jamesagnew I can do that, only thing is flyway is based either on jdbc or SQL scripts. And as far as I understand right how we use hibernate schema generation. Those two are not compatible as far as I know. Issue is that while hibernate can generate code for almost any db - with flyway one needs to provide specific DB support. Any you have in mind? Like postgre / SQL server / MySQL?

**Comment by anthonys123** [comment]
I think we should support PostgreSQL and SQL Server at a minimum.  Support for Derby migration is questionable because Derby should never really be used in a production setting.  I can say this having shipped a product using Derby and later regretting it.  :)

One way of approaching this with Flyway is to create two separate database instances, one with the old schema and one with the new, and let Flyway generate the migration script by reading the metadata of each.

Another way appears to be detailed here:

https://stackoverflow.com/questions/11071821/cdi-extension-for-flyway

**Comment by patrick-werner** [comment]
Nice topic! 
At our university we have a good experience in using [liquibase](https://www.liquibase.org/) for such tasks.
Liquibase integrates nice with Spring & Hibernate, can generate the migration script from the diff between DB schema and persistence entities (_liquibase:diff_), and supports schema rollbacks.
So from my experience i would suggest to go with liquibase.

When were changes to the DB schema made in the HAPI JPA server? Do we have a structured overview of DB changes over the release versions?
I think this analysis would be a good start to this topic.

**Comment by fil512** [comment]
Flyway migration is now integrated.
